# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define "linux" do |linux|
        linux.vm.box = "jtarpley/rocky9_cis"
    end

    config.vm.define "linuxpw" do |linuxpw|
        linuxpw.vm.box = "jtarpley/rocky9_cis"
        linuxpw.vm.provision "shell", upload_path: "/home/vagrant/vagrant-shell", inline: <<-SHELL
        sudo rm -rf /etc/sudoers.d/vagrant
        SHELL
    end

    config.vm.define "cmd" do |cmd|
        cmd.vm.box = "jtarpley/w2025_cis"
        cmd.vm.provision "shell", inline: <<-SHELL
        powershell.exe -NoProfile -NoLogo -Command "New-ItemProperty -Path 'HKLM:\\SOFTWARE\\OpenSSH' -Name DefaultShell -Value 'C:\\Windows\\System32\\cmd.exe' -PropertyType String -Force"
        powershell.exe -NoProfile -NoLogo -Command "Restart-Service sshd"
        SHELL
    end

    config.vm.define "windows" do |windows|
        windows.vm.box = "jtarpley/w2025_cis"
    end
end
