// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.6
// source: pkg/hclspec/hclspec.proto

package hclspec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrimitiveTypePB int32

const (
	PrimitiveTypePB_UNSPECIFIED PrimitiveTypePB = 0
	PrimitiveTypePB_STRING      PrimitiveTypePB = 1
	PrimitiveTypePB_NUMBER      PrimitiveTypePB = 2
	PrimitiveTypePB_BOOL        PrimitiveTypePB = 3
)

// Enum value maps for PrimitiveTypePB.
var (
	PrimitiveTypePB_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "STRING",
		2: "NUMBER",
		3: "BOOL",
	}
	PrimitiveTypePB_value = map[string]int32{
		"UNSPECIFIED": 0,
		"STRING":      1,
		"NUMBER":      2,
		"BOOL":        3,
	}
)

func (x PrimitiveTypePB) Enum() *PrimitiveTypePB {
	p := new(PrimitiveTypePB)
	*p = x
	return p
}

func (x PrimitiveTypePB) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PrimitiveTypePB) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_hclspec_hclspec_proto_enumTypes[0].Descriptor()
}

func (PrimitiveTypePB) Type() protoreflect.EnumType {
	return &file_pkg_hclspec_hclspec_proto_enumTypes[0]
}

func (x PrimitiveTypePB) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PrimitiveTypePB.Descriptor instead.
func (PrimitiveTypePB) EnumDescriptor() ([]byte, []int) {
	return file_pkg_hclspec_hclspec_proto_rawDescGZIP(), []int{0}
}

type AllowedValuesConstraintPB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *AllowedValuesConstraintPB) Reset() {
	*x = AllowedValuesConstraintPB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hclspec_hclspec_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllowedValuesConstraintPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowedValuesConstraintPB) ProtoMessage() {}

func (x *AllowedValuesConstraintPB) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hclspec_hclspec_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowedValuesConstraintPB.ProtoReflect.Descriptor instead.
func (*AllowedValuesConstraintPB) Descriptor() ([]byte, []int) {
	return file_pkg_hclspec_hclspec_proto_rawDescGZIP(), []int{0}
}

func (x *AllowedValuesConstraintPB) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type FieldConstraintPB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Constraint:
	//
	//	*FieldConstraintPB_AllowedValues
	Constraint isFieldConstraintPB_Constraint `protobuf_oneof:"constraint"`
}

func (x *FieldConstraintPB) Reset() {
	*x = FieldConstraintPB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hclspec_hclspec_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldConstraintPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldConstraintPB) ProtoMessage() {}

func (x *FieldConstraintPB) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hclspec_hclspec_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldConstraintPB.ProtoReflect.Descriptor instead.
func (*FieldConstraintPB) Descriptor() ([]byte, []int) {
	return file_pkg_hclspec_hclspec_proto_rawDescGZIP(), []int{1}
}

func (m *FieldConstraintPB) GetConstraint() isFieldConstraintPB_Constraint {
	if m != nil {
		return m.Constraint
	}
	return nil
}

func (x *FieldConstraintPB) GetAllowedValues() *AllowedValuesConstraintPB {
	if x, ok := x.GetConstraint().(*FieldConstraintPB_AllowedValues); ok {
		return x.AllowedValues
	}
	return nil
}

type isFieldConstraintPB_Constraint interface {
	isFieldConstraintPB_Constraint()
}

type FieldConstraintPB_AllowedValues struct {
	AllowedValues *AllowedValuesConstraintPB `protobuf:"bytes,1,opt,name=allowed_values,json=allowedValues,proto3,oneof"`
}

func (*FieldConstraintPB_AllowedValues) isFieldConstraintPB_Constraint() {}

type ObjectFieldPB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type         *TypePB              `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Required     bool                 `protobuf:"varint,2,opt,name=required,proto3" json:"required,omitempty"`
	Sensitive    bool                 `protobuf:"varint,3,opt,name=sensitive,proto3" json:"sensitive,omitempty"`
	DefaultValue []byte               `protobuf:"bytes,4,opt,name=default_value,json=defaultValue,proto3,oneof" json:"default_value,omitempty"`
	Aliases      []string             `protobuf:"bytes,5,rep,name=aliases,proto3" json:"aliases,omitempty"`
	Constraints  []*FieldConstraintPB `protobuf:"bytes,6,rep,name=constraints,proto3" json:"constraints,omitempty"`
}

func (x *ObjectFieldPB) Reset() {
	*x = ObjectFieldPB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hclspec_hclspec_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectFieldPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectFieldPB) ProtoMessage() {}

func (x *ObjectFieldPB) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hclspec_hclspec_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectFieldPB.ProtoReflect.Descriptor instead.
func (*ObjectFieldPB) Descriptor() ([]byte, []int) {
	return file_pkg_hclspec_hclspec_proto_rawDescGZIP(), []int{2}
}

func (x *ObjectFieldPB) GetType() *TypePB {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *ObjectFieldPB) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ObjectFieldPB) GetSensitive() bool {
	if x != nil {
		return x.Sensitive
	}
	return false
}

func (x *ObjectFieldPB) GetDefaultValue() []byte {
	if x != nil {
		return x.DefaultValue
	}
	return nil
}

func (x *ObjectFieldPB) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *ObjectFieldPB) GetConstraints() []*FieldConstraintPB {
	if x != nil {
		return x.Constraints
	}
	return nil
}

type FieldPresentConditionPB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
}

func (x *FieldPresentConditionPB) Reset() {
	*x = FieldPresentConditionPB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hclspec_hclspec_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldPresentConditionPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldPresentConditionPB) ProtoMessage() {}

func (x *FieldPresentConditionPB) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hclspec_hclspec_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldPresentConditionPB.ProtoReflect.Descriptor instead.
func (*FieldPresentConditionPB) Descriptor() ([]byte, []int) {
	return file_pkg_hclspec_hclspec_proto_rawDescGZIP(), []int{3}
}

func (x *FieldPresentConditionPB) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

type FieldNotPresentConditionPB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
}

func (x *FieldNotPresentConditionPB) Reset() {
	*x = FieldNotPresentConditionPB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hclspec_hclspec_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldNotPresentConditionPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldNotPresentConditionPB) ProtoMessage() {}

func (x *FieldNotPresentConditionPB) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hclspec_hclspec_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldNotPresentConditionPB.ProtoReflect.Descriptor instead.
func (*FieldNotPresentConditionPB) Descriptor() ([]byte, []int) {
	return file_pkg_hclspec_hclspec_proto_rawDescGZIP(), []int{4}
}

func (x *FieldNotPresentConditionPB) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

type FieldEqualsConditionPB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *FieldEqualsConditionPB) Reset() {
	*x = FieldEqualsConditionPB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hclspec_hclspec_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldEqualsConditionPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldEqualsConditionPB) ProtoMessage() {}

func (x *FieldEqualsConditionPB) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hclspec_hclspec_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldEqualsConditionPB.ProtoReflect.Descriptor instead.
func (*FieldEqualsConditionPB) Descriptor() ([]byte, []int) {
	return file_pkg_hclspec_hclspec_proto_rawDescGZIP(), []int{5}
}

func (x *FieldEqualsConditionPB) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *FieldEqualsConditionPB) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ObjectConditionPB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Condition:
	//
	//	*ObjectConditionPB_FieldPresent
	//	*ObjectConditionPB_FieldNotPresent
	//	*ObjectConditionPB_FieldEquals
	Condition isObjectConditionPB_Condition `protobuf_oneof:"condition"`
}

func (x *ObjectConditionPB) Reset() {
	*x = ObjectConditionPB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hclspec_hclspec_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectConditionPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectConditionPB) ProtoMessage() {}

func (x *ObjectConditionPB) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hclspec_hclspec_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectConditionPB.ProtoReflect.Descriptor instead.
func (*ObjectConditionPB) Descriptor() ([]byte, []int) {
	return file_pkg_hclspec_hclspec_proto_rawDescGZIP(), []int{6}
}

func (m *ObjectConditionPB) GetCondition() isObjectConditionPB_Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (x *ObjectConditionPB) GetFieldPresent() *FieldPresentConditionPB {
	if x, ok := x.GetCondition().(*ObjectConditionPB_FieldPresent); ok {
		return x.FieldPresent
	}
	return nil
}

func (x *ObjectConditionPB) GetFieldNotPresent() *FieldNotPresentConditionPB {
	if x, ok := x.GetCondition().(*ObjectConditionPB_FieldNotPresent); ok {
		return x.FieldNotPresent
	}
	return nil
}

func (x *ObjectConditionPB) GetFieldEquals() *FieldEqualsConditionPB {
	if x, ok := x.GetCondition().(*ObjectConditionPB_FieldEquals); ok {
		return x.FieldEquals
	}
	return nil
}

type isObjectConditionPB_Condition interface {
	isObjectConditionPB_Condition()
}

type ObjectConditionPB_FieldPresent struct {
	FieldPresent *FieldPresentConditionPB `protobuf:"bytes,1,opt,name=field_present,json=fieldPresent,proto3,oneof"`
}

type ObjectConditionPB_FieldNotPresent struct {
	FieldNotPresent *FieldNotPresentConditionPB `protobuf:"bytes,2,opt,name=field_not_present,json=fieldNotPresent,proto3,oneof"`
}

type ObjectConditionPB_FieldEquals struct {
	FieldEquals *FieldEqualsConditionPB `protobuf:"bytes,3,opt,name=field_equals,json=fieldEquals,proto3,oneof"`
}

func (*ObjectConditionPB_FieldPresent) isObjectConditionPB_Condition() {}

func (*ObjectConditionPB_FieldNotPresent) isObjectConditionPB_Condition() {}

func (*ObjectConditionPB_FieldEquals) isObjectConditionPB_Condition() {}

type MutuallyExclusiveConstraintPB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fields []string `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *MutuallyExclusiveConstraintPB) Reset() {
	*x = MutuallyExclusiveConstraintPB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hclspec_hclspec_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MutuallyExclusiveConstraintPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutuallyExclusiveConstraintPB) ProtoMessage() {}

func (x *MutuallyExclusiveConstraintPB) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hclspec_hclspec_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutuallyExclusiveConstraintPB.ProtoReflect.Descriptor instead.
func (*MutuallyExclusiveConstraintPB) Descriptor() ([]byte, []int) {
	return file_pkg_hclspec_hclspec_proto_rawDescGZIP(), []int{7}
}

func (x *MutuallyExclusiveConstraintPB) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type RequiredTogetherConstraintPB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fields []string `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *RequiredTogetherConstraintPB) Reset() {
	*x = RequiredTogetherConstraintPB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hclspec_hclspec_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequiredTogetherConstraintPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequiredTogetherConstraintPB) ProtoMessage() {}

func (x *RequiredTogetherConstraintPB) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hclspec_hclspec_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequiredTogetherConstraintPB.ProtoReflect.Descriptor instead.
func (*RequiredTogetherConstraintPB) Descriptor() ([]byte, []int) {
	return file_pkg_hclspec_hclspec_proto_rawDescGZIP(), []int{8}
}

func (x *RequiredTogetherConstraintPB) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type RequiredOneOfConstraintPB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fields []string `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *RequiredOneOfConstraintPB) Reset() {
	*x = RequiredOneOfConstraintPB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hclspec_hclspec_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequiredOneOfConstraintPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequiredOneOfConstraintPB) ProtoMessage() {}

func (x *RequiredOneOfConstraintPB) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hclspec_hclspec_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequiredOneOfConstraintPB.ProtoReflect.Descriptor instead.
func (*RequiredOneOfConstraintPB) Descriptor() ([]byte, []int) {
	return file_pkg_hclspec_hclspec_proto_rawDescGZIP(), []int{9}
}

func (x *RequiredOneOfConstraintPB) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type AllowedFieldValuesConstraintPB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field  string   `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Values [][]byte `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *AllowedFieldValuesConstraintPB) Reset() {
	*x = AllowedFieldValuesConstraintPB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hclspec_hclspec_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllowedFieldValuesConstraintPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowedFieldValuesConstraintPB) ProtoMessage() {}

func (x *AllowedFieldValuesConstraintPB) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hclspec_hclspec_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowedFieldValuesConstraintPB.ProtoReflect.Descriptor instead.
func (*AllowedFieldValuesConstraintPB) Descriptor() ([]byte, []int) {
	return file_pkg_hclspec_hclspec_proto_rawDescGZIP(), []int{10}
}

func (x *AllowedFieldValuesConstraintPB) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *AllowedFieldValuesConstraintPB) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type ConditionalConstraintPB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Condition  *ObjectConditionPB  `protobuf:"bytes,1,opt,name=condition,proto3" json:"condition,omitempty"`
	Constraint *ObjectConstraintPB `protobuf:"bytes,2,opt,name=constraint,proto3" json:"constraint,omitempty"`
}

func (x *ConditionalConstraintPB) Reset() {
	*x = ConditionalConstraintPB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hclspec_hclspec_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConditionalConstraintPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionalConstraintPB) ProtoMessage() {}

func (x *ConditionalConstraintPB) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hclspec_hclspec_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionalConstraintPB.ProtoReflect.Descriptor instead.
func (*ConditionalConstraintPB) Descriptor() ([]byte, []int) {
	return file_pkg_hclspec_hclspec_proto_rawDescGZIP(), []int{11}
}

func (x *ConditionalConstraintPB) GetCondition() *ObjectConditionPB {
	if x != nil {
		return x.Condition
	}
	return nil
}

func (x *ConditionalConstraintPB) GetConstraint() *ObjectConstraintPB {
	if x != nil {
		return x.Constraint
	}
	return nil
}

type ObjectConstraintPB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Constraint:
	//
	//	*ObjectConstraintPB_MutuallyExclusive
	//	*ObjectConstraintPB_RequiredTogether
	//	*ObjectConstraintPB_RequiredOneOf
	//	*ObjectConstraintPB_AllowedFieldValues
	//	*ObjectConstraintPB_Conditional
	Constraint isObjectConstraintPB_Constraint `protobuf_oneof:"constraint"`
}

func (x *ObjectConstraintPB) Reset() {
	*x = ObjectConstraintPB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hclspec_hclspec_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectConstraintPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectConstraintPB) ProtoMessage() {}

func (x *ObjectConstraintPB) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hclspec_hclspec_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectConstraintPB.ProtoReflect.Descriptor instead.
func (*ObjectConstraintPB) Descriptor() ([]byte, []int) {
	return file_pkg_hclspec_hclspec_proto_rawDescGZIP(), []int{12}
}

func (m *ObjectConstraintPB) GetConstraint() isObjectConstraintPB_Constraint {
	if m != nil {
		return m.Constraint
	}
	return nil
}

func (x *ObjectConstraintPB) GetMutuallyExclusive() *MutuallyExclusiveConstraintPB {
	if x, ok := x.GetConstraint().(*ObjectConstraintPB_MutuallyExclusive); ok {
		return x.MutuallyExclusive
	}
	return nil
}

func (x *ObjectConstraintPB) GetRequiredTogether() *RequiredTogetherConstraintPB {
	if x, ok := x.GetConstraint().(*ObjectConstraintPB_RequiredTogether); ok {
		return x.RequiredTogether
	}
	return nil
}

func (x *ObjectConstraintPB) GetRequiredOneOf() *RequiredOneOfConstraintPB {
	if x, ok := x.GetConstraint().(*ObjectConstraintPB_RequiredOneOf); ok {
		return x.RequiredOneOf
	}
	return nil
}

func (x *ObjectConstraintPB) GetAllowedFieldValues() *AllowedFieldValuesConstraintPB {
	if x, ok := x.GetConstraint().(*ObjectConstraintPB_AllowedFieldValues); ok {
		return x.AllowedFieldValues
	}
	return nil
}

func (x *ObjectConstraintPB) GetConditional() *ConditionalConstraintPB {
	if x, ok := x.GetConstraint().(*ObjectConstraintPB_Conditional); ok {
		return x.Conditional
	}
	return nil
}

type isObjectConstraintPB_Constraint interface {
	isObjectConstraintPB_Constraint()
}

type ObjectConstraintPB_MutuallyExclusive struct {
	MutuallyExclusive *MutuallyExclusiveConstraintPB `protobuf:"bytes,1,opt,name=mutually_exclusive,json=mutuallyExclusive,proto3,oneof"`
}

type ObjectConstraintPB_RequiredTogether struct {
	RequiredTogether *RequiredTogetherConstraintPB `protobuf:"bytes,2,opt,name=required_together,json=requiredTogether,proto3,oneof"`
}

type ObjectConstraintPB_RequiredOneOf struct {
	RequiredOneOf *RequiredOneOfConstraintPB `protobuf:"bytes,3,opt,name=required_one_of,json=requiredOneOf,proto3,oneof"`
}

type ObjectConstraintPB_AllowedFieldValues struct {
	AllowedFieldValues *AllowedFieldValuesConstraintPB `protobuf:"bytes,4,opt,name=allowed_field_values,json=allowedFieldValues,proto3,oneof"`
}

type ObjectConstraintPB_Conditional struct {
	Conditional *ConditionalConstraintPB `protobuf:"bytes,5,opt,name=conditional,proto3,oneof"`
}

func (*ObjectConstraintPB_MutuallyExclusive) isObjectConstraintPB_Constraint() {}

func (*ObjectConstraintPB_RequiredTogether) isObjectConstraintPB_Constraint() {}

func (*ObjectConstraintPB_RequiredOneOf) isObjectConstraintPB_Constraint() {}

func (*ObjectConstraintPB_AllowedFieldValues) isObjectConstraintPB_Constraint() {}

func (*ObjectConstraintPB_Conditional) isObjectConstraintPB_Constraint() {}

type ObjectTypePB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fields      map[string]*ObjectFieldPB `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Constraints []*ObjectConstraintPB     `protobuf:"bytes,2,rep,name=constraints,proto3" json:"constraints,omitempty"`
}

func (x *ObjectTypePB) Reset() {
	*x = ObjectTypePB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hclspec_hclspec_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectTypePB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectTypePB) ProtoMessage() {}

func (x *ObjectTypePB) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hclspec_hclspec_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectTypePB.ProtoReflect.Descriptor instead.
func (*ObjectTypePB) Descriptor() ([]byte, []int) {
	return file_pkg_hclspec_hclspec_proto_rawDescGZIP(), []int{13}
}

func (x *ObjectTypePB) GetFields() map[string]*ObjectFieldPB {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *ObjectTypePB) GetConstraints() []*ObjectConstraintPB {
	if x != nil {
		return x.Constraints
	}
	return nil
}

type ListTypePB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ElementType *TypePB `protobuf:"bytes,1,opt,name=element_type,json=elementType,proto3" json:"element_type,omitempty"`
}

func (x *ListTypePB) Reset() {
	*x = ListTypePB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hclspec_hclspec_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTypePB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTypePB) ProtoMessage() {}

func (x *ListTypePB) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hclspec_hclspec_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTypePB.ProtoReflect.Descriptor instead.
func (*ListTypePB) Descriptor() ([]byte, []int) {
	return file_pkg_hclspec_hclspec_proto_rawDescGZIP(), []int{14}
}

func (x *ListTypePB) GetElementType() *TypePB {
	if x != nil {
		return x.ElementType
	}
	return nil
}

type SetTypePB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ElementType *TypePB `protobuf:"bytes,1,opt,name=element_type,json=elementType,proto3" json:"element_type,omitempty"`
}

func (x *SetTypePB) Reset() {
	*x = SetTypePB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hclspec_hclspec_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetTypePB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTypePB) ProtoMessage() {}

func (x *SetTypePB) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hclspec_hclspec_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTypePB.ProtoReflect.Descriptor instead.
func (*SetTypePB) Descriptor() ([]byte, []int) {
	return file_pkg_hclspec_hclspec_proto_rawDescGZIP(), []int{15}
}

func (x *SetTypePB) GetElementType() *TypePB {
	if x != nil {
		return x.ElementType
	}
	return nil
}

type MapTypePB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ElementType *TypePB `protobuf:"bytes,1,opt,name=element_type,json=elementType,proto3" json:"element_type,omitempty"`
}

func (x *MapTypePB) Reset() {
	*x = MapTypePB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hclspec_hclspec_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapTypePB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapTypePB) ProtoMessage() {}

func (x *MapTypePB) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hclspec_hclspec_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapTypePB.ProtoReflect.Descriptor instead.
func (*MapTypePB) Descriptor() ([]byte, []int) {
	return file_pkg_hclspec_hclspec_proto_rawDescGZIP(), []int{16}
}

func (x *MapTypePB) GetElementType() *TypePB {
	if x != nil {
		return x.ElementType
	}
	return nil
}

type DurationTypePB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DurationTypePB) Reset() {
	*x = DurationTypePB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hclspec_hclspec_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DurationTypePB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurationTypePB) ProtoMessage() {}

func (x *DurationTypePB) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hclspec_hclspec_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurationTypePB.ProtoReflect.Descriptor instead.
func (*DurationTypePB) Descriptor() ([]byte, []int) {
	return file_pkg_hclspec_hclspec_proto_rawDescGZIP(), []int{17}
}

type SensitiveStringTypePB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SensitiveStringTypePB) Reset() {
	*x = SensitiveStringTypePB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hclspec_hclspec_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SensitiveStringTypePB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensitiveStringTypePB) ProtoMessage() {}

func (x *SensitiveStringTypePB) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hclspec_hclspec_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensitiveStringTypePB.ProtoReflect.Descriptor instead.
func (*SensitiveStringTypePB) Descriptor() ([]byte, []int) {
	return file_pkg_hclspec_hclspec_proto_rawDescGZIP(), []int{18}
}

type RawTypePB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RawTypePB) Reset() {
	*x = RawTypePB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hclspec_hclspec_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawTypePB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawTypePB) ProtoMessage() {}

func (x *RawTypePB) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hclspec_hclspec_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawTypePB.ProtoReflect.Descriptor instead.
func (*RawTypePB) Descriptor() ([]byte, []int) {
	return file_pkg_hclspec_hclspec_proto_rawDescGZIP(), []int{19}
}

type TypePB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//
	//	*TypePB_Object
	//	*TypePB_Primitive
	//	*TypePB_List
	//	*TypePB_Set
	//	*TypePB_Map
	//	*TypePB_Duration
	//	*TypePB_SensitiveString
	//	*TypePB_Raw
	Type isTypePB_Type `protobuf_oneof:"type"`
}

func (x *TypePB) Reset() {
	*x = TypePB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hclspec_hclspec_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TypePB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypePB) ProtoMessage() {}

func (x *TypePB) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hclspec_hclspec_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypePB.ProtoReflect.Descriptor instead.
func (*TypePB) Descriptor() ([]byte, []int) {
	return file_pkg_hclspec_hclspec_proto_rawDescGZIP(), []int{20}
}

func (m *TypePB) GetType() isTypePB_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *TypePB) GetObject() *ObjectTypePB {
	if x, ok := x.GetType().(*TypePB_Object); ok {
		return x.Object
	}
	return nil
}

func (x *TypePB) GetPrimitive() PrimitiveTypePB {
	if x, ok := x.GetType().(*TypePB_Primitive); ok {
		return x.Primitive
	}
	return PrimitiveTypePB_UNSPECIFIED
}

func (x *TypePB) GetList() *ListTypePB {
	if x, ok := x.GetType().(*TypePB_List); ok {
		return x.List
	}
	return nil
}

func (x *TypePB) GetSet() *SetTypePB {
	if x, ok := x.GetType().(*TypePB_Set); ok {
		return x.Set
	}
	return nil
}

func (x *TypePB) GetMap() *MapTypePB {
	if x, ok := x.GetType().(*TypePB_Map); ok {
		return x.Map
	}
	return nil
}

func (x *TypePB) GetDuration() *DurationTypePB {
	if x, ok := x.GetType().(*TypePB_Duration); ok {
		return x.Duration
	}
	return nil
}

func (x *TypePB) GetSensitiveString() *SensitiveStringTypePB {
	if x, ok := x.GetType().(*TypePB_SensitiveString); ok {
		return x.SensitiveString
	}
	return nil
}

func (x *TypePB) GetRaw() *RawTypePB {
	if x, ok := x.GetType().(*TypePB_Raw); ok {
		return x.Raw
	}
	return nil
}

type isTypePB_Type interface {
	isTypePB_Type()
}

type TypePB_Object struct {
	Object *ObjectTypePB `protobuf:"bytes,1,opt,name=object,proto3,oneof"`
}

type TypePB_Primitive struct {
	Primitive PrimitiveTypePB `protobuf:"varint,2,opt,name=primitive,proto3,enum=hclspec.PrimitiveTypePB,oneof"`
}

type TypePB_List struct {
	List *ListTypePB `protobuf:"bytes,3,opt,name=list,proto3,oneof"`
}

type TypePB_Set struct {
	Set *SetTypePB `protobuf:"bytes,4,opt,name=set,proto3,oneof"`
}

type TypePB_Map struct {
	Map *MapTypePB `protobuf:"bytes,5,opt,name=map,proto3,oneof"`
}

type TypePB_Duration struct {
	Duration *DurationTypePB `protobuf:"bytes,6,opt,name=duration,proto3,oneof"`
}

type TypePB_SensitiveString struct {
	SensitiveString *SensitiveStringTypePB `protobuf:"bytes,7,opt,name=sensitive_string,json=sensitiveString,proto3,oneof"`
}

type TypePB_Raw struct {
	Raw *RawTypePB `protobuf:"bytes,8,opt,name=raw,proto3,oneof"`
}

func (*TypePB_Object) isTypePB_Type() {}

func (*TypePB_Primitive) isTypePB_Type() {}

func (*TypePB_List) isTypePB_Type() {}

func (*TypePB_Set) isTypePB_Type() {}

func (*TypePB_Map) isTypePB_Type() {}

func (*TypePB_Duration) isTypePB_Type() {}

func (*TypePB_SensitiveString) isTypePB_Type() {}

func (*TypePB_Raw) isTypePB_Type() {}

type SpecPB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Object *ObjectTypePB `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
}

func (x *SpecPB) Reset() {
	*x = SpecPB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hclspec_hclspec_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpecPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecPB) ProtoMessage() {}

func (x *SpecPB) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hclspec_hclspec_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecPB.ProtoReflect.Descriptor instead.
func (*SpecPB) Descriptor() ([]byte, []int) {
	return file_pkg_hclspec_hclspec_proto_rawDescGZIP(), []int{21}
}

func (x *SpecPB) GetObject() *ObjectTypePB {
	if x != nil {
		return x.Object
	}
	return nil
}

var File_pkg_hclspec_hclspec_proto protoreflect.FileDescriptor

var file_pkg_hclspec_hclspec_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x6b, 0x67, 0x2f, 0x68, 0x63, 0x6c, 0x73, 0x70, 0x65, 0x63, 0x2f, 0x68, 0x63,
	0x6c, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x68, 0x63, 0x6c,
	0x73, 0x70, 0x65, 0x63, 0x22, 0x33, 0x0a, 0x19, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x50,
	0x42, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0c, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x6e, 0x0a, 0x11, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x50, 0x42, 0x12, 0x4b,
	0x0a, 0x0e, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x68, 0x63, 0x6c, 0x73, 0x70, 0x65, 0x63,
	0x2e, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x43, 0x6f,
	0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x50, 0x42, 0x48, 0x00, 0x52, 0x0d, 0x61, 0x6c,
	0x6c, 0x6f, 0x77, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x42, 0x0c, 0x0a, 0x0a, 0x63,
	0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x22, 0x82, 0x02, 0x0a, 0x0d, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x50, 0x42, 0x12, 0x23, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x68, 0x63, 0x6c, 0x73,
	0x70, 0x65, 0x63, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x50, 0x42, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x73, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x12, 0x28, 0x0a, 0x0d, 0x64, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0c, 0x48, 0x00, 0x52, 0x0c, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x88, 0x01, 0x01, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x65, 0x73, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x65, 0x73, 0x12, 0x3c,
	0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x68, 0x63, 0x6c, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x50, 0x42, 0x52,
	0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x42, 0x10, 0x0a, 0x0e,
	0x5f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2f,
	0x0a, 0x17, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x43, 0x6f,
	0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x42, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x22,
	0x32, 0x0a, 0x1a, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4e, 0x6f, 0x74, 0x50, 0x72, 0x65, 0x73, 0x65,
	0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x42, 0x12, 0x14, 0x0a,
	0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x22, 0x44, 0x0a, 0x16, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x45, 0x71, 0x75, 0x61,
	0x6c, 0x73, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x42, 0x12, 0x14, 0x0a,
	0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x82, 0x02, 0x0a, 0x11, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x42, 0x12,
	0x47, 0x0a, 0x0d, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x68, 0x63, 0x6c, 0x73, 0x70, 0x65, 0x63,
	0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e,
	0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x42, 0x48, 0x00, 0x52, 0x0c, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x12, 0x51, 0x0a, 0x11, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x5f, 0x6e, 0x6f, 0x74, 0x5f, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x68, 0x63, 0x6c, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x4e, 0x6f, 0x74, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e,
	0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x42, 0x48, 0x00, 0x52, 0x0f, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x4e, 0x6f, 0x74, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x12, 0x44, 0x0a, 0x0c, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x5f, 0x65, 0x71, 0x75, 0x61, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1f, 0x2e, 0x68, 0x63, 0x6c, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x45, 0x71, 0x75, 0x61, 0x6c, 0x73, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x50, 0x42, 0x48, 0x00, 0x52, 0x0b, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x45, 0x71, 0x75, 0x61, 0x6c,
	0x73, 0x42, 0x0b, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x37,
	0x0a, 0x1d, 0x4d, 0x75, 0x74, 0x75, 0x61, 0x6c, 0x6c, 0x79, 0x45, 0x78, 0x63, 0x6c, 0x75, 0x73,
	0x69, 0x76, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x50, 0x42, 0x12,
	0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0x36, 0x0a, 0x1c, 0x52, 0x65, 0x71, 0x75, 0x69,
	0x72, 0x65, 0x64, 0x54, 0x6f, 0x67, 0x65, 0x74, 0x68, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x74,
	0x72, 0x61, 0x69, 0x6e, 0x74, 0x50, 0x42, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22,
	0x33, 0x0a, 0x19, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x4f, 0x6e, 0x65, 0x4f, 0x66,
	0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x50, 0x42, 0x12, 0x16, 0x0a, 0x06,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x22, 0x4e, 0x0a, 0x1e, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72,
	0x61, 0x69, 0x6e, 0x74, 0x50, 0x42, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x22, 0x90, 0x01, 0x0a, 0x17, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x50, 0x42,
	0x12, 0x38, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x68, 0x63, 0x6c, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x42, 0x52,
	0x09, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3b, 0x0a, 0x0a, 0x63, 0x6f,
	0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x68, 0x63, 0x6c, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x43,
	0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x50, 0x42, 0x52, 0x0a, 0x63, 0x6f, 0x6e,
	0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x22, 0xc2, 0x03, 0x0a, 0x12, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x50, 0x42, 0x12, 0x57,
	0x0a, 0x12, 0x6d, 0x75, 0x74, 0x75, 0x61, 0x6c, 0x6c, 0x79, 0x5f, 0x65, 0x78, 0x63, 0x6c, 0x75,
	0x73, 0x69, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x68, 0x63, 0x6c,
	0x73, 0x70, 0x65, 0x63, 0x2e, 0x4d, 0x75, 0x74, 0x75, 0x61, 0x6c, 0x6c, 0x79, 0x45, 0x78, 0x63,
	0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74,
	0x50, 0x42, 0x48, 0x00, 0x52, 0x11, 0x6d, 0x75, 0x74, 0x75, 0x61, 0x6c, 0x6c, 0x79, 0x45, 0x78,
	0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x12, 0x54, 0x0a, 0x11, 0x72, 0x65, 0x71, 0x75, 0x69,
	0x72, 0x65, 0x64, 0x5f, 0x74, 0x6f, 0x67, 0x65, 0x74, 0x68, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x25, 0x2e, 0x68, 0x63, 0x6c, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x69, 0x72, 0x65, 0x64, 0x54, 0x6f, 0x67, 0x65, 0x74, 0x68, 0x65, 0x72, 0x43, 0x6f, 0x6e,
	0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x50, 0x42, 0x48, 0x00, 0x52, 0x10, 0x72, 0x65, 0x71,
	0x75, 0x69, 0x72, 0x65, 0x64, 0x54, 0x6f, 0x67, 0x65, 0x74, 0x68, 0x65, 0x72, 0x12, 0x4c, 0x0a,
	0x0f, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x6f, 0x6e, 0x65, 0x5f, 0x6f, 0x66,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x68, 0x63, 0x6c, 0x73, 0x70, 0x65, 0x63,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x4f, 0x6e, 0x65, 0x4f, 0x66, 0x43, 0x6f,
	0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x50, 0x42, 0x48, 0x00, 0x52, 0x0d, 0x72, 0x65,
	0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x4f, 0x6e, 0x65, 0x4f, 0x66, 0x12, 0x5b, 0x0a, 0x14, 0x61,
	0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x68, 0x63, 0x6c, 0x73,
	0x70, 0x65, 0x63, 0x2e, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74,
	0x50, 0x42, 0x48, 0x00, 0x52, 0x12, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x44, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e,
	0x68, 0x63, 0x6c, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x50, 0x42, 0x48,
	0x00, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x42, 0x0c,
	0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x22, 0xdb, 0x01, 0x0a,
	0x0c, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x50, 0x42, 0x12, 0x39, 0x0a,
	0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e,
	0x68, 0x63, 0x6c, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x50, 0x42, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x3d, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x73,
	0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x68, 0x63, 0x6c, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x43, 0x6f,
	0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x50, 0x42, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x73,
	0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x1a, 0x51, 0x0a, 0x0b, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x68, 0x63, 0x6c, 0x73, 0x70, 0x65,
	0x63, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x50, 0x42, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x40, 0x0a, 0x0a, 0x4c, 0x69,
	0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x50, 0x42, 0x12, 0x32, 0x0a, 0x0c, 0x65, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x68, 0x63, 0x6c, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x50, 0x42, 0x52,
	0x0b, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x3f, 0x0a, 0x09,
	0x53, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x50, 0x42, 0x12, 0x32, 0x0a, 0x0c, 0x65, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x68, 0x63, 0x6c, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x50, 0x42,
	0x52, 0x0b, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x3f, 0x0a,
	0x09, 0x4d, 0x61, 0x70, 0x54, 0x79, 0x70, 0x65, 0x50, 0x42, 0x12, 0x32, 0x0a, 0x0c, 0x65, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x68, 0x63, 0x6c, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x50,
	0x42, 0x52, 0x0b, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x10,
	0x0a, 0x0e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x50, 0x42,
	0x22, 0x17, 0x0a, 0x15, 0x53, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x50, 0x42, 0x22, 0x0b, 0x0a, 0x09, 0x52, 0x61, 0x77,
	0x54, 0x79, 0x70, 0x65, 0x50, 0x42, 0x22, 0xa2, 0x03, 0x0a, 0x06, 0x54, 0x79, 0x70, 0x65, 0x50,
	0x42, 0x12, 0x2f, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x68, 0x63, 0x6c, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x50, 0x42, 0x48, 0x00, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x70, 0x72, 0x69, 0x6d, 0x69, 0x74, 0x69, 0x76, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x68, 0x63, 0x6c, 0x73, 0x70, 0x65, 0x63, 0x2e,
	0x50, 0x72, 0x69, 0x6d, 0x69, 0x74, 0x69, 0x76, 0x65, 0x54, 0x79, 0x70, 0x65, 0x50, 0x42, 0x48,
	0x00, 0x52, 0x09, 0x70, 0x72, 0x69, 0x6d, 0x69, 0x74, 0x69, 0x76, 0x65, 0x12, 0x29, 0x0a, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x68, 0x63, 0x6c,
	0x73, 0x70, 0x65, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x50, 0x42, 0x48,
	0x00, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x03, 0x73, 0x65, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x68, 0x63, 0x6c, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x53,
	0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x50, 0x42, 0x48, 0x00, 0x52, 0x03, 0x73, 0x65, 0x74, 0x12,
	0x26, 0x0a, 0x03, 0x6d, 0x61, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x68,
	0x63, 0x6c, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x4d, 0x61, 0x70, 0x54, 0x79, 0x70, 0x65, 0x50, 0x42,
	0x48, 0x00, 0x52, 0x03, 0x6d, 0x61, 0x70, 0x12, 0x35, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x68, 0x63, 0x6c, 0x73,
	0x70, 0x65, 0x63, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x50, 0x42, 0x48, 0x00, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x4b,
	0x0a, 0x10, 0x73, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x73, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x68, 0x63, 0x6c, 0x73, 0x70,
	0x65, 0x63, 0x2e, 0x53, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x50, 0x42, 0x48, 0x00, 0x52, 0x0f, 0x73, 0x65, 0x6e, 0x73,
	0x69, 0x74, 0x69, 0x76, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x26, 0x0a, 0x03, 0x72,
	0x61, 0x77, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x68, 0x63, 0x6c, 0x73, 0x70,
	0x65, 0x63, 0x2e, 0x52, 0x61, 0x77, 0x54, 0x79, 0x70, 0x65, 0x50, 0x42, 0x48, 0x00, 0x52, 0x03,
	0x72, 0x61, 0x77, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x37, 0x0a, 0x06, 0x53,
	0x70, 0x65, 0x63, 0x50, 0x42, 0x12, 0x2d, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x68, 0x63, 0x6c, 0x73, 0x70, 0x65, 0x63, 0x2e,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x50, 0x42, 0x52, 0x06, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x2a, 0x44, 0x0a, 0x0f, 0x50, 0x72, 0x69, 0x6d, 0x69, 0x74, 0x69, 0x76,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x50, 0x42, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x52, 0x49,
	0x4e, 0x47, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x55, 0x4d, 0x42, 0x45, 0x52, 0x10, 0x02,
	0x12, 0x08, 0x0a, 0x04, 0x42, 0x4f, 0x4f, 0x4c, 0x10, 0x03, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x72, 0x69, 0x70, 0x70, 0x73, 0x6f,
	0x66, 0x74, 0x2f, 0x66, 0x6f, 0x72, 0x67, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x68, 0x63, 0x6c,
	0x73, 0x70, 0x65, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_hclspec_hclspec_proto_rawDescOnce sync.Once
	file_pkg_hclspec_hclspec_proto_rawDescData = file_pkg_hclspec_hclspec_proto_rawDesc
)

func file_pkg_hclspec_hclspec_proto_rawDescGZIP() []byte {
	file_pkg_hclspec_hclspec_proto_rawDescOnce.Do(func() {
		file_pkg_hclspec_hclspec_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_hclspec_hclspec_proto_rawDescData)
	})
	return file_pkg_hclspec_hclspec_proto_rawDescData
}

var file_pkg_hclspec_hclspec_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_hclspec_hclspec_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_pkg_hclspec_hclspec_proto_goTypes = []interface{}{
	(PrimitiveTypePB)(0),                   // 0: hclspec.PrimitiveTypePB
	(*AllowedValuesConstraintPB)(nil),      // 1: hclspec.AllowedValuesConstraintPB
	(*FieldConstraintPB)(nil),              // 2: hclspec.FieldConstraintPB
	(*ObjectFieldPB)(nil),                  // 3: hclspec.ObjectFieldPB
	(*FieldPresentConditionPB)(nil),        // 4: hclspec.FieldPresentConditionPB
	(*FieldNotPresentConditionPB)(nil),     // 5: hclspec.FieldNotPresentConditionPB
	(*FieldEqualsConditionPB)(nil),         // 6: hclspec.FieldEqualsConditionPB
	(*ObjectConditionPB)(nil),              // 7: hclspec.ObjectConditionPB
	(*MutuallyExclusiveConstraintPB)(nil),  // 8: hclspec.MutuallyExclusiveConstraintPB
	(*RequiredTogetherConstraintPB)(nil),   // 9: hclspec.RequiredTogetherConstraintPB
	(*RequiredOneOfConstraintPB)(nil),      // 10: hclspec.RequiredOneOfConstraintPB
	(*AllowedFieldValuesConstraintPB)(nil), // 11: hclspec.AllowedFieldValuesConstraintPB
	(*ConditionalConstraintPB)(nil),        // 12: hclspec.ConditionalConstraintPB
	(*ObjectConstraintPB)(nil),             // 13: hclspec.ObjectConstraintPB
	(*ObjectTypePB)(nil),                   // 14: hclspec.ObjectTypePB
	(*ListTypePB)(nil),                     // 15: hclspec.ListTypePB
	(*SetTypePB)(nil),                      // 16: hclspec.SetTypePB
	(*MapTypePB)(nil),                      // 17: hclspec.MapTypePB
	(*DurationTypePB)(nil),                 // 18: hclspec.DurationTypePB
	(*SensitiveStringTypePB)(nil),          // 19: hclspec.SensitiveStringTypePB
	(*RawTypePB)(nil),                      // 20: hclspec.RawTypePB
	(*TypePB)(nil),                         // 21: hclspec.TypePB
	(*SpecPB)(nil),                         // 22: hclspec.SpecPB
	nil,                                    // 23: hclspec.ObjectTypePB.FieldsEntry
}
var file_pkg_hclspec_hclspec_proto_depIdxs = []int32{
	1,  // 0: hclspec.FieldConstraintPB.allowed_values:type_name -> hclspec.AllowedValuesConstraintPB
	21, // 1: hclspec.ObjectFieldPB.type:type_name -> hclspec.TypePB
	2,  // 2: hclspec.ObjectFieldPB.constraints:type_name -> hclspec.FieldConstraintPB
	4,  // 3: hclspec.ObjectConditionPB.field_present:type_name -> hclspec.FieldPresentConditionPB
	5,  // 4: hclspec.ObjectConditionPB.field_not_present:type_name -> hclspec.FieldNotPresentConditionPB
	6,  // 5: hclspec.ObjectConditionPB.field_equals:type_name -> hclspec.FieldEqualsConditionPB
	7,  // 6: hclspec.ConditionalConstraintPB.condition:type_name -> hclspec.ObjectConditionPB
	13, // 7: hclspec.ConditionalConstraintPB.constraint:type_name -> hclspec.ObjectConstraintPB
	8,  // 8: hclspec.ObjectConstraintPB.mutually_exclusive:type_name -> hclspec.MutuallyExclusiveConstraintPB
	9,  // 9: hclspec.ObjectConstraintPB.required_together:type_name -> hclspec.RequiredTogetherConstraintPB
	10, // 10: hclspec.ObjectConstraintPB.required_one_of:type_name -> hclspec.RequiredOneOfConstraintPB
	11, // 11: hclspec.ObjectConstraintPB.allowed_field_values:type_name -> hclspec.AllowedFieldValuesConstraintPB
	12, // 12: hclspec.ObjectConstraintPB.conditional:type_name -> hclspec.ConditionalConstraintPB
	23, // 13: hclspec.ObjectTypePB.fields:type_name -> hclspec.ObjectTypePB.FieldsEntry
	13, // 14: hclspec.ObjectTypePB.constraints:type_name -> hclspec.ObjectConstraintPB
	21, // 15: hclspec.ListTypePB.element_type:type_name -> hclspec.TypePB
	21, // 16: hclspec.SetTypePB.element_type:type_name -> hclspec.TypePB
	21, // 17: hclspec.MapTypePB.element_type:type_name -> hclspec.TypePB
	14, // 18: hclspec.TypePB.object:type_name -> hclspec.ObjectTypePB
	0,  // 19: hclspec.TypePB.primitive:type_name -> hclspec.PrimitiveTypePB
	15, // 20: hclspec.TypePB.list:type_name -> hclspec.ListTypePB
	16, // 21: hclspec.TypePB.set:type_name -> hclspec.SetTypePB
	17, // 22: hclspec.TypePB.map:type_name -> hclspec.MapTypePB
	18, // 23: hclspec.TypePB.duration:type_name -> hclspec.DurationTypePB
	19, // 24: hclspec.TypePB.sensitive_string:type_name -> hclspec.SensitiveStringTypePB
	20, // 25: hclspec.TypePB.raw:type_name -> hclspec.RawTypePB
	14, // 26: hclspec.SpecPB.object:type_name -> hclspec.ObjectTypePB
	3,  // 27: hclspec.ObjectTypePB.FieldsEntry.value:type_name -> hclspec.ObjectFieldPB
	28, // [28:28] is the sub-list for method output_type
	28, // [28:28] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_pkg_hclspec_hclspec_proto_init() }
func file_pkg_hclspec_hclspec_proto_init() {
	if File_pkg_hclspec_hclspec_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_hclspec_hclspec_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllowedValuesConstraintPB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hclspec_hclspec_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldConstraintPB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hclspec_hclspec_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectFieldPB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hclspec_hclspec_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldPresentConditionPB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hclspec_hclspec_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldNotPresentConditionPB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hclspec_hclspec_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldEqualsConditionPB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hclspec_hclspec_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectConditionPB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hclspec_hclspec_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MutuallyExclusiveConstraintPB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hclspec_hclspec_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequiredTogetherConstraintPB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hclspec_hclspec_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequiredOneOfConstraintPB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hclspec_hclspec_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllowedFieldValuesConstraintPB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hclspec_hclspec_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConditionalConstraintPB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hclspec_hclspec_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectConstraintPB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hclspec_hclspec_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectTypePB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hclspec_hclspec_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTypePB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hclspec_hclspec_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetTypePB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hclspec_hclspec_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapTypePB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hclspec_hclspec_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DurationTypePB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hclspec_hclspec_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SensitiveStringTypePB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hclspec_hclspec_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawTypePB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hclspec_hclspec_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TypePB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hclspec_hclspec_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpecPB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_hclspec_hclspec_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*FieldConstraintPB_AllowedValues)(nil),
	}
	file_pkg_hclspec_hclspec_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_pkg_hclspec_hclspec_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*ObjectConditionPB_FieldPresent)(nil),
		(*ObjectConditionPB_FieldNotPresent)(nil),
		(*ObjectConditionPB_FieldEquals)(nil),
	}
	file_pkg_hclspec_hclspec_proto_msgTypes[12].OneofWrappers = []interface{}{
		(*ObjectConstraintPB_MutuallyExclusive)(nil),
		(*ObjectConstraintPB_RequiredTogether)(nil),
		(*ObjectConstraintPB_RequiredOneOf)(nil),
		(*ObjectConstraintPB_AllowedFieldValues)(nil),
		(*ObjectConstraintPB_Conditional)(nil),
	}
	file_pkg_hclspec_hclspec_proto_msgTypes[20].OneofWrappers = []interface{}{
		(*TypePB_Object)(nil),
		(*TypePB_Primitive)(nil),
		(*TypePB_List)(nil),
		(*TypePB_Set)(nil),
		(*TypePB_Map)(nil),
		(*TypePB_Duration)(nil),
		(*TypePB_SensitiveString)(nil),
		(*TypePB_Raw)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_hclspec_hclspec_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_hclspec_hclspec_proto_goTypes,
		DependencyIndexes: file_pkg_hclspec_hclspec_proto_depIdxs,
		EnumInfos:         file_pkg_hclspec_hclspec_proto_enumTypes,
		MessageInfos:      file_pkg_hclspec_hclspec_proto_msgTypes,
	}.Build()
	File_pkg_hclspec_hclspec_proto = out.File
	file_pkg_hclspec_hclspec_proto_rawDesc = nil
	file_pkg_hclspec_hclspec_proto_goTypes = nil
	file_pkg_hclspec_hclspec_proto_depIdxs = nil
}
