syntax = "proto3";

package hclspec;

option go_package = "github.com/trippsoft/forge/pkg/hclspec";

message RawTypePB {}

enum SimpleTypeDataPB {
    UNSPECIFIED = 0;
    BOOL = 1;
    STRING = 2;
    SENSITIVE_STRING = 3;
}

message AllowedValuesConstraintPB {
    repeated bytes values = 1;
}

message MutuallyExclusiveConstraintPB {
    repeated string fields = 1;
}

message RequiredTogetherConstraintPB {
    repeated string fields = 1;
}

message RequireOneOfConstraintPB {
    repeated string fields = 1;
}

message AllowedFieldValuesConstraintPB {
    string field = 1;
    repeated bytes values = 2;
}

message FieldPresentConditionPB {
    string field = 1;
}

message FieldNotPresentConditionPB {
    string field = 1;
}

message FieldEqualsConditionPB {
    string field = 1;
    bytes value = 2;
}

message TypeConditionPB {
    oneof condition {
        FieldPresentConditionPB field_present = 1;
        FieldNotPresentConditionPB field_not_present = 2;
        FieldEqualsConditionPB field_equals = 3;
    }
}

message ConditionalConstraintPB {
    TypeConditionPB condition = 1;
    TypeConstraintPB constraint = 2;
}

message TypeConstraintPB {
    oneof constraint {
        AllowedValuesConstraintPB allowed_values = 1;
        MutuallyExclusiveConstraintPB mutually_exclusive = 2;
        RequiredTogetherConstraintPB required_together = 3;
        RequireOneOfConstraintPB require_one_of = 4;
        AllowedFieldValuesConstraintPB allowed_field_values = 5;
        ConditionalConstraintPB conditional = 6;
    }
}

message SimpleTypePB {
    SimpleTypeDataPB data = 1;
    repeated TypeConstraintPB constraints = 2;
}

message IntegerTypePB {
    bool signed = 1;
    int32 bit_size = 2;
    repeated TypeConstraintPB constraints = 3;
}

message FloatTypePB {
    int32 bit_size = 1;
    repeated TypeConstraintPB constraints = 2;
}

message SetTypePB {
    TypePB element_type = 1;
    repeated TypeConstraintPB constraints = 2;
}

message ListTypePB {
    TypePB element_type = 1;
    repeated TypeConstraintPB constraints = 2;
}

message MapTypePB {
    TypePB element_type = 1;
    repeated TypeConstraintPB constraints = 2;
}

message ObjectFieldPB {
    TypePB type = 1;
    bool required = 2;
    optional bytes default_value = 3;
    repeated string aliases = 4;
}

message ObjectTypePB {
    map<string, ObjectFieldPB> fields = 1;
    repeated TypeConstraintPB constraints = 2;
}

message TypePB {
    oneof type {
        RawTypePB raw = 1;
        SimpleTypePB simple = 2;
        IntegerTypePB integer = 3;
        FloatTypePB float = 4;
        SetTypePB set = 5;
        ListTypePB list = 6;
        MapTypePB map = 7;
        ObjectTypePB object = 8;
    }
}

message SpecPB {
    ObjectTypePB object = 1;
}
