// Code generated by scriptimport.  DO NOT EDIT.

// This script is used to discover AppArmor status on Linux systems.
// It returns 1 if AppArmor is enabled, 0 otherwise.

package info

const apparmorDiscoveryScript = `` +
    `if [ -d /sys/kernel/security/apparmor ]; then ` +
    `apparmor_enabled=1; ` +
    `else ` +
    `apparmor_enabled=0; ` +
    `fi; ` +
    `echo "$apparmor_enabled"`
