// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.6
// source: pkg/info/discovery_plugin.proto

package info

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	DiscoveryPlugin_DiscoverInfo_FullMethodName = "/info.DiscoveryPlugin/DiscoverInfo"
	DiscoveryPlugin_Shutdown_FullMethodName     = "/info.DiscoveryPlugin/Shutdown"
)

// DiscoveryPluginClient is the client API for DiscoveryPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DiscoveryPluginClient interface {
	DiscoverInfo(ctx context.Context, in *DiscoverInfoRequest, opts ...grpc.CallOption) (*DiscoverInfoResponse, error)
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
}

type discoveryPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewDiscoveryPluginClient(cc grpc.ClientConnInterface) DiscoveryPluginClient {
	return &discoveryPluginClient{cc}
}

func (c *discoveryPluginClient) DiscoverInfo(ctx context.Context, in *DiscoverInfoRequest, opts ...grpc.CallOption) (*DiscoverInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscoverInfoResponse)
	err := c.cc.Invoke(ctx, DiscoveryPlugin_DiscoverInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryPluginClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, DiscoveryPlugin_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiscoveryPluginServer is the server API for DiscoveryPlugin service.
// All implementations must embed UnimplementedDiscoveryPluginServer
// for forward compatibility
type DiscoveryPluginServer interface {
	DiscoverInfo(context.Context, *DiscoverInfoRequest) (*DiscoverInfoResponse, error)
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	mustEmbedUnimplementedDiscoveryPluginServer()
}

// UnimplementedDiscoveryPluginServer must be embedded to have forward compatible implementations.
type UnimplementedDiscoveryPluginServer struct {
}

func (UnimplementedDiscoveryPluginServer) DiscoverInfo(context.Context, *DiscoverInfoRequest) (*DiscoverInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiscoverInfo not implemented")
}
func (UnimplementedDiscoveryPluginServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedDiscoveryPluginServer) mustEmbedUnimplementedDiscoveryPluginServer() {}

// UnsafeDiscoveryPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiscoveryPluginServer will
// result in compilation errors.
type UnsafeDiscoveryPluginServer interface {
	mustEmbedUnimplementedDiscoveryPluginServer()
}

func RegisterDiscoveryPluginServer(s grpc.ServiceRegistrar, srv DiscoveryPluginServer) {
	s.RegisterService(&DiscoveryPlugin_ServiceDesc, srv)
}

func _DiscoveryPlugin_DiscoverInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryPluginServer).DiscoverInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoveryPlugin_DiscoverInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryPluginServer).DiscoverInfo(ctx, req.(*DiscoverInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscoveryPlugin_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryPluginServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoveryPlugin_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryPluginServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DiscoveryPlugin_ServiceDesc is the grpc.ServiceDesc for DiscoveryPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiscoveryPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "info.DiscoveryPlugin",
	HandlerType: (*DiscoveryPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DiscoverInfo",
			Handler:    _DiscoveryPlugin_DiscoverInfo_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _DiscoveryPlugin_Shutdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/info/discovery_plugin.proto",
}
