// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.6
// source: discovery_plugin.proto

package info

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiscoverInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DiscoverInfoRequest) Reset() {
	*x = DiscoverInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_discovery_plugin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiscoverInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverInfoRequest) ProtoMessage() {}

func (x *DiscoverInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_plugin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverInfoRequest.ProtoReflect.Descriptor instead.
func (*DiscoverInfoRequest) Descriptor() ([]byte, []int) {
	return file_discovery_plugin_proto_rawDescGZIP(), []int{0}
}

type OSInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FriendlyName string   `protobuf:"bytes,2,opt,name=friendly_name,json=friendlyName,proto3" json:"friendly_name,omitempty"`
	Release      string   `protobuf:"bytes,3,opt,name=release,proto3" json:"release,omitempty"`
	ReleaseId    string   `protobuf:"bytes,4,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	MajorVersion string   `protobuf:"bytes,5,opt,name=major_version,json=majorVersion,proto3" json:"major_version,omitempty"`
	Version      string   `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	Edition      string   `protobuf:"bytes,7,opt,name=edition,proto3" json:"edition,omitempty"`
	EditionId    string   `protobuf:"bytes,8,opt,name=edition_id,json=editionId,proto3" json:"edition_id,omitempty"`
	Families     []string `protobuf:"bytes,9,rep,name=families,proto3" json:"families,omitempty"`
}

func (x *OSInfoResponse) Reset() {
	*x = OSInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_discovery_plugin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OSInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSInfoResponse) ProtoMessage() {}

func (x *OSInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_plugin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSInfoResponse.ProtoReflect.Descriptor instead.
func (*OSInfoResponse) Descriptor() ([]byte, []int) {
	return file_discovery_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *OSInfoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OSInfoResponse) GetFriendlyName() string {
	if x != nil {
		return x.FriendlyName
	}
	return ""
}

func (x *OSInfoResponse) GetRelease() string {
	if x != nil {
		return x.Release
	}
	return ""
}

func (x *OSInfoResponse) GetReleaseId() string {
	if x != nil {
		return x.ReleaseId
	}
	return ""
}

func (x *OSInfoResponse) GetMajorVersion() string {
	if x != nil {
		return x.MajorVersion
	}
	return ""
}

func (x *OSInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *OSInfoResponse) GetEdition() string {
	if x != nil {
		return x.Edition
	}
	return ""
}

func (x *OSInfoResponse) GetEditionId() string {
	if x != nil {
		return x.EditionId
	}
	return ""
}

func (x *OSInfoResponse) GetFamilies() []string {
	if x != nil {
		return x.Families
	}
	return nil
}

type FIPSInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Known   bool `protobuf:"varint,1,opt,name=known,proto3" json:"known,omitempty"`
	Enabled bool `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
}

func (x *FIPSInfoResponse) Reset() {
	*x = FIPSInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_discovery_plugin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FIPSInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FIPSInfoResponse) ProtoMessage() {}

func (x *FIPSInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_plugin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FIPSInfoResponse.ProtoReflect.Descriptor instead.
func (*FIPSInfoResponse) Descriptor() ([]byte, []int) {
	return file_discovery_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *FIPSInfoResponse) GetKnown() bool {
	if x != nil {
		return x.Known
	}
	return false
}

func (x *FIPSInfoResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type AppArmorInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Supported bool `protobuf:"varint,1,opt,name=supported,proto3" json:"supported,omitempty"`
	Enabled   bool `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
}

func (x *AppArmorInfoResponse) Reset() {
	*x = AppArmorInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_discovery_plugin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppArmorInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppArmorInfoResponse) ProtoMessage() {}

func (x *AppArmorInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_plugin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppArmorInfoResponse.ProtoReflect.Descriptor instead.
func (*AppArmorInfoResponse) Descriptor() ([]byte, []int) {
	return file_discovery_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *AppArmorInfoResponse) GetSupported() bool {
	if x != nil {
		return x.Supported
	}
	return false
}

func (x *AppArmorInfoResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type SELinuxInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Supported bool   `protobuf:"varint,1,opt,name=supported,proto3" json:"supported,omitempty"`
	Installed bool   `protobuf:"varint,2,opt,name=installed,proto3" json:"installed,omitempty"`
	Status    string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Type      string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *SELinuxInfoResponse) Reset() {
	*x = SELinuxInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_discovery_plugin_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SELinuxInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SELinuxInfoResponse) ProtoMessage() {}

func (x *SELinuxInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_plugin_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SELinuxInfoResponse.ProtoReflect.Descriptor instead.
func (*SELinuxInfoResponse) Descriptor() ([]byte, []int) {
	return file_discovery_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *SELinuxInfoResponse) GetSupported() bool {
	if x != nil {
		return x.Supported
	}
	return false
}

func (x *SELinuxInfoResponse) GetInstalled() bool {
	if x != nil {
		return x.Installed
	}
	return false
}

func (x *SELinuxInfoResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SELinuxInfoResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type PackageManagerInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *PackageManagerInfoResponse) Reset() {
	*x = PackageManagerInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_discovery_plugin_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PackageManagerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageManagerInfoResponse) ProtoMessage() {}

func (x *PackageManagerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_plugin_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageManagerInfoResponse.ProtoReflect.Descriptor instead.
func (*PackageManagerInfoResponse) Descriptor() ([]byte, []int) {
	return file_discovery_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *PackageManagerInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PackageManagerInfoResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ServiceManagerInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ServiceManagerInfoResponse) Reset() {
	*x = ServiceManagerInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_discovery_plugin_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceManagerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceManagerInfoResponse) ProtoMessage() {}

func (x *ServiceManagerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_plugin_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceManagerInfoResponse.ProtoReflect.Descriptor instead.
func (*ServiceManagerInfoResponse) Descriptor() ([]byte, []int) {
	return file_discovery_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *ServiceManagerInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DiscoverInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Os             *OSInfoResponse             `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Fips           *FIPSInfoResponse           `protobuf:"bytes,2,opt,name=fips,proto3" json:"fips,omitempty"`
	AppArmor       *AppArmorInfoResponse       `protobuf:"bytes,3,opt,name=app_armor,json=appArmor,proto3" json:"app_armor,omitempty"`
	Selinux        *SELinuxInfoResponse        `protobuf:"bytes,4,opt,name=selinux,proto3" json:"selinux,omitempty"`
	PackageManager *PackageManagerInfoResponse `protobuf:"bytes,5,opt,name=package_manager,json=packageManager,proto3" json:"package_manager,omitempty"`
	ServiceManager *ServiceManagerInfoResponse `protobuf:"bytes,6,opt,name=service_manager,json=serviceManager,proto3" json:"service_manager,omitempty"`
}

func (x *DiscoverInfoResponse) Reset() {
	*x = DiscoverInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_discovery_plugin_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiscoverInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverInfoResponse) ProtoMessage() {}

func (x *DiscoverInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_plugin_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverInfoResponse.ProtoReflect.Descriptor instead.
func (*DiscoverInfoResponse) Descriptor() ([]byte, []int) {
	return file_discovery_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *DiscoverInfoResponse) GetOs() *OSInfoResponse {
	if x != nil {
		return x.Os
	}
	return nil
}

func (x *DiscoverInfoResponse) GetFips() *FIPSInfoResponse {
	if x != nil {
		return x.Fips
	}
	return nil
}

func (x *DiscoverInfoResponse) GetAppArmor() *AppArmorInfoResponse {
	if x != nil {
		return x.AppArmor
	}
	return nil
}

func (x *DiscoverInfoResponse) GetSelinux() *SELinuxInfoResponse {
	if x != nil {
		return x.Selinux
	}
	return nil
}

func (x *DiscoverInfoResponse) GetPackageManager() *PackageManagerInfoResponse {
	if x != nil {
		return x.PackageManager
	}
	return nil
}

func (x *DiscoverInfoResponse) GetServiceManager() *ServiceManagerInfoResponse {
	if x != nil {
		return x.ServiceManager
	}
	return nil
}

type ShutdownRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_discovery_plugin_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_plugin_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_discovery_plugin_proto_rawDescGZIP(), []int{8}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_discovery_plugin_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_plugin_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_discovery_plugin_proto_rawDescGZIP(), []int{9}
}

var File_discovery_plugin_proto protoreflect.FileDescriptor

var file_discovery_plugin_proto_rawDesc = []byte{
	0x0a, 0x16, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x5f, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x15,
	0x0a, 0x13, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x92, 0x02, 0x0a, 0x0e, 0x4f, 0x53, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x6c, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x6c, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x6c, 0x65, 0x61,
	0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x6c,
	0x65, 0x61, 0x73, 0x65, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x61, 0x6a, 0x6f, 0x72, 0x5f,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d,
	0x61, 0x6a, 0x6f, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1d, 0x0a, 0x0a, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x69, 0x65, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x08, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x69, 0x65, 0x73, 0x22, 0x42, 0x0a, 0x10, 0x46, 0x49,
	0x50, 0x53, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x6b,
	0x6e, 0x6f, 0x77, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x22, 0x4e,
	0x0a, 0x14, 0x41, 0x70, 0x70, 0x41, 0x72, 0x6d, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72,
	0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x73, 0x75, 0x70, 0x70, 0x6f,
	0x72, 0x74, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x22, 0x7d,
	0x0a, 0x13, 0x53, 0x45, 0x4c, 0x69, 0x6e, 0x75, 0x78, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74,
	0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72,
	0x74, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x65, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x65,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x44, 0x0a,
	0x1a, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x22, 0x30, 0x0a, 0x1a, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xec, 0x02, 0x0a, 0x14, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24,
	0x0a, 0x02, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x69, 0x6e, 0x66,
	0x6f, 0x2e, 0x4f, 0x53, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x52, 0x02, 0x6f, 0x73, 0x12, 0x2a, 0x0a, 0x04, 0x66, 0x69, 0x70, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x46, 0x49, 0x50, 0x53, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x66, 0x69, 0x70, 0x73,
	0x12, 0x37, 0x0a, 0x09, 0x61, 0x70, 0x70, 0x5f, 0x61, 0x72, 0x6d, 0x6f, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x41, 0x70, 0x70, 0x41, 0x72,
	0x6d, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52,
	0x08, 0x61, 0x70, 0x70, 0x41, 0x72, 0x6d, 0x6f, 0x72, 0x12, 0x33, 0x0a, 0x07, 0x73, 0x65, 0x6c,
	0x69, 0x6e, 0x75, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x69, 0x6e, 0x66,
	0x6f, 0x2e, 0x53, 0x45, 0x4c, 0x69, 0x6e, 0x75, 0x78, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x07, 0x73, 0x65, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x12, 0x49,
	0x0a, 0x0f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x50,
	0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0e, 0x70, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12, 0x49, 0x0a, 0x0f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x20, 0x2e, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x22, 0x11, 0x0a, 0x0f, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x53, 0x68, 0x75, 0x74, 0x64,
	0x6f, 0x77, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x93, 0x01, 0x0a, 0x0f,
	0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x12,
	0x45, 0x0a, 0x0c, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x19, 0x2e, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x69, 0x6e, 0x66,
	0x6f, 0x2e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x08, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f,
	0x77, 0x6e, 0x12, 0x15, 0x2e, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f,
	0x77, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x69, 0x6e, 0x66, 0x6f,
	0x2e, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x74, 0x72, 0x69, 0x70, 0x70, 0x73, 0x6f, 0x66, 0x74, 0x2f, 0x66, 0x6f, 0x72, 0x67, 0x65, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x69, 0x6e, 0x66, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_discovery_plugin_proto_rawDescOnce sync.Once
	file_discovery_plugin_proto_rawDescData = file_discovery_plugin_proto_rawDesc
)

func file_discovery_plugin_proto_rawDescGZIP() []byte {
	file_discovery_plugin_proto_rawDescOnce.Do(func() {
		file_discovery_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(file_discovery_plugin_proto_rawDescData)
	})
	return file_discovery_plugin_proto_rawDescData
}

var file_discovery_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_discovery_plugin_proto_goTypes = []interface{}{
	(*DiscoverInfoRequest)(nil),        // 0: info.DiscoverInfoRequest
	(*OSInfoResponse)(nil),             // 1: info.OSInfoResponse
	(*FIPSInfoResponse)(nil),           // 2: info.FIPSInfoResponse
	(*AppArmorInfoResponse)(nil),       // 3: info.AppArmorInfoResponse
	(*SELinuxInfoResponse)(nil),        // 4: info.SELinuxInfoResponse
	(*PackageManagerInfoResponse)(nil), // 5: info.PackageManagerInfoResponse
	(*ServiceManagerInfoResponse)(nil), // 6: info.ServiceManagerInfoResponse
	(*DiscoverInfoResponse)(nil),       // 7: info.DiscoverInfoResponse
	(*ShutdownRequest)(nil),            // 8: info.ShutdownRequest
	(*ShutdownResponse)(nil),           // 9: info.ShutdownResponse
}
var file_discovery_plugin_proto_depIdxs = []int32{
	1, // 0: info.DiscoverInfoResponse.os:type_name -> info.OSInfoResponse
	2, // 1: info.DiscoverInfoResponse.fips:type_name -> info.FIPSInfoResponse
	3, // 2: info.DiscoverInfoResponse.app_armor:type_name -> info.AppArmorInfoResponse
	4, // 3: info.DiscoverInfoResponse.selinux:type_name -> info.SELinuxInfoResponse
	5, // 4: info.DiscoverInfoResponse.package_manager:type_name -> info.PackageManagerInfoResponse
	6, // 5: info.DiscoverInfoResponse.service_manager:type_name -> info.ServiceManagerInfoResponse
	0, // 6: info.DiscoveryPlugin.DiscoverInfo:input_type -> info.DiscoverInfoRequest
	8, // 7: info.DiscoveryPlugin.Shutdown:input_type -> info.ShutdownRequest
	7, // 8: info.DiscoveryPlugin.DiscoverInfo:output_type -> info.DiscoverInfoResponse
	9, // 9: info.DiscoveryPlugin.Shutdown:output_type -> info.ShutdownResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_discovery_plugin_proto_init() }
func file_discovery_plugin_proto_init() {
	if File_discovery_plugin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_discovery_plugin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiscoverInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_discovery_plugin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OSInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_discovery_plugin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FIPSInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_discovery_plugin_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppArmorInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_discovery_plugin_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SELinuxInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_discovery_plugin_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PackageManagerInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_discovery_plugin_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceManagerInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_discovery_plugin_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiscoverInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_discovery_plugin_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShutdownRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_discovery_plugin_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShutdownResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_discovery_plugin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_discovery_plugin_proto_goTypes,
		DependencyIndexes: file_discovery_plugin_proto_depIdxs,
		MessageInfos:      file_discovery_plugin_proto_msgTypes,
	}.Build()
	File_discovery_plugin_proto = out.File
	file_discovery_plugin_proto_rawDesc = nil
	file_discovery_plugin_proto_goTypes = nil
	file_discovery_plugin_proto_depIdxs = nil
}
