// Code generated by scriptimport.  DO NOT EDIT.

// This script is used to discover FIPS mode status on Linux systems.
// It returns 1 if FIPS mode is enabled, 0 otherwise.

package info

const fipsLinuxDiscoveryScript = `` +
    `if [ -f /proc/sys/crypto/fips_enabled ]; then ` +
    `fips_enabled=$(cat /proc/sys/crypto/fips_enabled); ` +
    `else ` +
    `fips_enabled=0; ` +
    `fi; ` +
    `echo "$fips_enabled"`
