// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.6
// source: pkg/info/info.proto

package info

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OSInfoPB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kernel       string   `protobuf:"bytes,1,opt,name=kernel,proto3" json:"kernel,omitempty"`
	Id           string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	FriendlyName string   `protobuf:"bytes,3,opt,name=friendly_name,json=friendlyName,proto3" json:"friendly_name,omitempty"`
	Release      string   `protobuf:"bytes,4,opt,name=release,proto3" json:"release,omitempty"`
	ReleaseId    string   `protobuf:"bytes,5,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	MajorVersion string   `protobuf:"bytes,6,opt,name=major_version,json=majorVersion,proto3" json:"major_version,omitempty"`
	Version      string   `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	Edition      string   `protobuf:"bytes,8,opt,name=edition,proto3" json:"edition,omitempty"`
	EditionId    string   `protobuf:"bytes,9,opt,name=edition_id,json=editionId,proto3" json:"edition_id,omitempty"`
	Arch         string   `protobuf:"bytes,10,opt,name=arch,proto3" json:"arch,omitempty"`
	Families     []string `protobuf:"bytes,11,rep,name=families,proto3" json:"families,omitempty"`
}

func (x *OSInfoPB) Reset() {
	*x = OSInfoPB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_info_info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OSInfoPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSInfoPB) ProtoMessage() {}

func (x *OSInfoPB) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_info_info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSInfoPB.ProtoReflect.Descriptor instead.
func (*OSInfoPB) Descriptor() ([]byte, []int) {
	return file_pkg_info_info_proto_rawDescGZIP(), []int{0}
}

func (x *OSInfoPB) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *OSInfoPB) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OSInfoPB) GetFriendlyName() string {
	if x != nil {
		return x.FriendlyName
	}
	return ""
}

func (x *OSInfoPB) GetRelease() string {
	if x != nil {
		return x.Release
	}
	return ""
}

func (x *OSInfoPB) GetReleaseId() string {
	if x != nil {
		return x.ReleaseId
	}
	return ""
}

func (x *OSInfoPB) GetMajorVersion() string {
	if x != nil {
		return x.MajorVersion
	}
	return ""
}

func (x *OSInfoPB) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *OSInfoPB) GetEdition() string {
	if x != nil {
		return x.Edition
	}
	return ""
}

func (x *OSInfoPB) GetEditionId() string {
	if x != nil {
		return x.EditionId
	}
	return ""
}

func (x *OSInfoPB) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *OSInfoPB) GetFamilies() []string {
	if x != nil {
		return x.Families
	}
	return nil
}

type FIPSInfoPB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Known   bool `protobuf:"varint,1,opt,name=known,proto3" json:"known,omitempty"`
	Enabled bool `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
}

func (x *FIPSInfoPB) Reset() {
	*x = FIPSInfoPB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_info_info_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FIPSInfoPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FIPSInfoPB) ProtoMessage() {}

func (x *FIPSInfoPB) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_info_info_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FIPSInfoPB.ProtoReflect.Descriptor instead.
func (*FIPSInfoPB) Descriptor() ([]byte, []int) {
	return file_pkg_info_info_proto_rawDescGZIP(), []int{1}
}

func (x *FIPSInfoPB) GetKnown() bool {
	if x != nil {
		return x.Known
	}
	return false
}

func (x *FIPSInfoPB) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type AppArmorInfoPB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Supported bool `protobuf:"varint,1,opt,name=supported,proto3" json:"supported,omitempty"`
	Enabled   bool `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
}

func (x *AppArmorInfoPB) Reset() {
	*x = AppArmorInfoPB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_info_info_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppArmorInfoPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppArmorInfoPB) ProtoMessage() {}

func (x *AppArmorInfoPB) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_info_info_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppArmorInfoPB.ProtoReflect.Descriptor instead.
func (*AppArmorInfoPB) Descriptor() ([]byte, []int) {
	return file_pkg_info_info_proto_rawDescGZIP(), []int{2}
}

func (x *AppArmorInfoPB) GetSupported() bool {
	if x != nil {
		return x.Supported
	}
	return false
}

func (x *AppArmorInfoPB) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type SELinuxInfoPB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Supported bool   `protobuf:"varint,1,opt,name=supported,proto3" json:"supported,omitempty"`
	Installed bool   `protobuf:"varint,2,opt,name=installed,proto3" json:"installed,omitempty"`
	Status    string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Type      string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *SELinuxInfoPB) Reset() {
	*x = SELinuxInfoPB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_info_info_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SELinuxInfoPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SELinuxInfoPB) ProtoMessage() {}

func (x *SELinuxInfoPB) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_info_info_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SELinuxInfoPB.ProtoReflect.Descriptor instead.
func (*SELinuxInfoPB) Descriptor() ([]byte, []int) {
	return file_pkg_info_info_proto_rawDescGZIP(), []int{3}
}

func (x *SELinuxInfoPB) GetSupported() bool {
	if x != nil {
		return x.Supported
	}
	return false
}

func (x *SELinuxInfoPB) GetInstalled() bool {
	if x != nil {
		return x.Installed
	}
	return false
}

func (x *SELinuxInfoPB) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SELinuxInfoPB) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type PackageManagerInfoPB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *PackageManagerInfoPB) Reset() {
	*x = PackageManagerInfoPB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_info_info_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PackageManagerInfoPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageManagerInfoPB) ProtoMessage() {}

func (x *PackageManagerInfoPB) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_info_info_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageManagerInfoPB.ProtoReflect.Descriptor instead.
func (*PackageManagerInfoPB) Descriptor() ([]byte, []int) {
	return file_pkg_info_info_proto_rawDescGZIP(), []int{4}
}

func (x *PackageManagerInfoPB) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PackageManagerInfoPB) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ServiceManagerInfoPB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ServiceManagerInfoPB) Reset() {
	*x = ServiceManagerInfoPB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_info_info_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceManagerInfoPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceManagerInfoPB) ProtoMessage() {}

func (x *ServiceManagerInfoPB) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_info_info_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceManagerInfoPB.ProtoReflect.Descriptor instead.
func (*ServiceManagerInfoPB) Descriptor() ([]byte, []int) {
	return file_pkg_info_info_proto_rawDescGZIP(), []int{5}
}

func (x *ServiceManagerInfoPB) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HostInfoPB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Os             *OSInfoPB             `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Fips           *FIPSInfoPB           `protobuf:"bytes,2,opt,name=fips,proto3" json:"fips,omitempty"`
	AppArmor       *AppArmorInfoPB       `protobuf:"bytes,3,opt,name=app_armor,json=appArmor,proto3" json:"app_armor,omitempty"`
	Selinux        *SELinuxInfoPB        `protobuf:"bytes,4,opt,name=selinux,proto3" json:"selinux,omitempty"`
	PackageManager *PackageManagerInfoPB `protobuf:"bytes,5,opt,name=package_manager,json=packageManager,proto3" json:"package_manager,omitempty"`
	ServiceManager *ServiceManagerInfoPB `protobuf:"bytes,6,opt,name=service_manager,json=serviceManager,proto3" json:"service_manager,omitempty"`
}

func (x *HostInfoPB) Reset() {
	*x = HostInfoPB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_info_info_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostInfoPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfoPB) ProtoMessage() {}

func (x *HostInfoPB) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_info_info_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfoPB.ProtoReflect.Descriptor instead.
func (*HostInfoPB) Descriptor() ([]byte, []int) {
	return file_pkg_info_info_proto_rawDescGZIP(), []int{6}
}

func (x *HostInfoPB) GetOs() *OSInfoPB {
	if x != nil {
		return x.Os
	}
	return nil
}

func (x *HostInfoPB) GetFips() *FIPSInfoPB {
	if x != nil {
		return x.Fips
	}
	return nil
}

func (x *HostInfoPB) GetAppArmor() *AppArmorInfoPB {
	if x != nil {
		return x.AppArmor
	}
	return nil
}

func (x *HostInfoPB) GetSelinux() *SELinuxInfoPB {
	if x != nil {
		return x.Selinux
	}
	return nil
}

func (x *HostInfoPB) GetPackageManager() *PackageManagerInfoPB {
	if x != nil {
		return x.PackageManager
	}
	return nil
}

func (x *HostInfoPB) GetServiceManager() *ServiceManagerInfoPB {
	if x != nil {
		return x.ServiceManager
	}
	return nil
}

var File_pkg_info_info_proto protoreflect.FileDescriptor

var file_pkg_info_info_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x6b, 0x67, 0x2f, 0x69, 0x6e, 0x66, 0x6f, 0x2f, 0x69, 0x6e, 0x66, 0x6f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0xb8, 0x02, 0x0a, 0x08,
	0x4f, 0x53, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x42, 0x12, 0x16, 0x0a, 0x06, 0x6b, 0x65, 0x72, 0x6e,
	0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x23, 0x0a, 0x0d, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x6c, 0x79, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x6c,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x49, 0x64, 0x12, 0x23,
	0x0a, 0x0d, 0x6d, 0x61, 0x6a, 0x6f, 0x72, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x61, 0x6a, 0x6f, 0x72, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a,
	0x07, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x65, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x64, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x64, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x63, 0x68, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x63, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x61,
	0x6d, 0x69, 0x6c, 0x69, 0x65, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x66, 0x61,
	0x6d, 0x69, 0x6c, 0x69, 0x65, 0x73, 0x22, 0x3c, 0x0a, 0x0a, 0x46, 0x49, 0x50, 0x53, 0x49, 0x6e,
	0x66, 0x6f, 0x50, 0x42, 0x12, 0x14, 0x0a, 0x05, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e,
	0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x64, 0x22, 0x48, 0x0a, 0x0e, 0x41, 0x70, 0x70, 0x41, 0x72, 0x6d, 0x6f, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x50, 0x42, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72,
	0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x73, 0x75, 0x70, 0x70, 0x6f,
	0x72, 0x74, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x22, 0x77,
	0x0a, 0x0d, 0x53, 0x45, 0x4c, 0x69, 0x6e, 0x75, 0x78, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x42, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x09, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x3e, 0x0a, 0x14, 0x50, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x42, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x2a, 0x0a, 0x14, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x42, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0xbe, 0x02, 0x0a, 0x0a, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x50, 0x42, 0x12, 0x1e, 0x0a, 0x02, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x4f, 0x53, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x42, 0x52, 0x02,
	0x6f, 0x73, 0x12, 0x24, 0x0a, 0x04, 0x66, 0x69, 0x70, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x46, 0x49, 0x50, 0x53, 0x49, 0x6e, 0x66, 0x6f,
	0x50, 0x42, 0x52, 0x04, 0x66, 0x69, 0x70, 0x73, 0x12, 0x31, 0x0a, 0x09, 0x61, 0x70, 0x70, 0x5f,
	0x61, 0x72, 0x6d, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x69, 0x6e,
	0x66, 0x6f, 0x2e, 0x41, 0x70, 0x70, 0x41, 0x72, 0x6d, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x50,
	0x42, 0x52, 0x08, 0x61, 0x70, 0x70, 0x41, 0x72, 0x6d, 0x6f, 0x72, 0x12, 0x2d, 0x0a, 0x07, 0x73,
	0x65, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x69,
	0x6e, 0x66, 0x6f, 0x2e, 0x53, 0x45, 0x4c, 0x69, 0x6e, 0x75, 0x78, 0x49, 0x6e, 0x66, 0x6f, 0x50,
	0x42, 0x52, 0x07, 0x73, 0x65, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x12, 0x43, 0x0a, 0x0f, 0x70, 0x61,
	0x63, 0x6b, 0x61, 0x67, 0x65, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x42, 0x52,
	0x0e, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12,
	0x43, 0x0a, 0x0f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x69, 0x6e, 0x66, 0x6f, 0x2e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x50, 0x42, 0x52, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x74, 0x72, 0x69, 0x70, 0x70, 0x73, 0x6f, 0x66, 0x74, 0x2f, 0x66, 0x6f, 0x72,
	0x67, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x69, 0x6e, 0x66, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_pkg_info_info_proto_rawDescOnce sync.Once
	file_pkg_info_info_proto_rawDescData = file_pkg_info_info_proto_rawDesc
)

func file_pkg_info_info_proto_rawDescGZIP() []byte {
	file_pkg_info_info_proto_rawDescOnce.Do(func() {
		file_pkg_info_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_info_info_proto_rawDescData)
	})
	return file_pkg_info_info_proto_rawDescData
}

var file_pkg_info_info_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_info_info_proto_goTypes = []interface{}{
	(*OSInfoPB)(nil),             // 0: info.OSInfoPB
	(*FIPSInfoPB)(nil),           // 1: info.FIPSInfoPB
	(*AppArmorInfoPB)(nil),       // 2: info.AppArmorInfoPB
	(*SELinuxInfoPB)(nil),        // 3: info.SELinuxInfoPB
	(*PackageManagerInfoPB)(nil), // 4: info.PackageManagerInfoPB
	(*ServiceManagerInfoPB)(nil), // 5: info.ServiceManagerInfoPB
	(*HostInfoPB)(nil),           // 6: info.HostInfoPB
}
var file_pkg_info_info_proto_depIdxs = []int32{
	0, // 0: info.HostInfoPB.os:type_name -> info.OSInfoPB
	1, // 1: info.HostInfoPB.fips:type_name -> info.FIPSInfoPB
	2, // 2: info.HostInfoPB.app_armor:type_name -> info.AppArmorInfoPB
	3, // 3: info.HostInfoPB.selinux:type_name -> info.SELinuxInfoPB
	4, // 4: info.HostInfoPB.package_manager:type_name -> info.PackageManagerInfoPB
	5, // 5: info.HostInfoPB.service_manager:type_name -> info.ServiceManagerInfoPB
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_info_info_proto_init() }
func file_pkg_info_info_proto_init() {
	if File_pkg_info_info_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_info_info_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OSInfoPB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_info_info_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FIPSInfoPB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_info_info_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppArmorInfoPB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_info_info_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SELinuxInfoPB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_info_info_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PackageManagerInfoPB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_info_info_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceManagerInfoPB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_info_info_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostInfoPB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_info_info_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_info_info_proto_goTypes,
		DependencyIndexes: file_pkg_info_info_proto_depIdxs,
		MessageInfos:      file_pkg_info_info_proto_msgTypes,
	}.Build()
	File_pkg_info_info_proto = out.File
	file_pkg_info_info_proto_rawDesc = nil
	file_pkg_info_info_proto_goTypes = nil
	file_pkg_info_info_proto_depIdxs = nil
}
