// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.6
// source: pkg/info/info.proto

package info

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OSInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kernel       string   `protobuf:"bytes,1,opt,name=kernel,proto3" json:"kernel,omitempty"`
	Id           string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	FriendlyName string   `protobuf:"bytes,3,opt,name=friendly_name,json=friendlyName,proto3" json:"friendly_name,omitempty"`
	Release      string   `protobuf:"bytes,4,opt,name=release,proto3" json:"release,omitempty"`
	ReleaseId    string   `protobuf:"bytes,5,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	MajorVersion string   `protobuf:"bytes,6,opt,name=major_version,json=majorVersion,proto3" json:"major_version,omitempty"`
	Version      string   `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	Edition      string   `protobuf:"bytes,8,opt,name=edition,proto3" json:"edition,omitempty"`
	EditionId    string   `protobuf:"bytes,9,opt,name=edition_id,json=editionId,proto3" json:"edition_id,omitempty"`
	Arch         string   `protobuf:"bytes,10,opt,name=arch,proto3" json:"arch,omitempty"`
	Families     []string `protobuf:"bytes,11,rep,name=families,proto3" json:"families,omitempty"`
}

func (x *OSInfo) Reset() {
	*x = OSInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_info_info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OSInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSInfo) ProtoMessage() {}

func (x *OSInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_info_info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSInfo.ProtoReflect.Descriptor instead.
func (*OSInfo) Descriptor() ([]byte, []int) {
	return file_pkg_info_info_proto_rawDescGZIP(), []int{0}
}

func (x *OSInfo) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *OSInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OSInfo) GetFriendlyName() string {
	if x != nil {
		return x.FriendlyName
	}
	return ""
}

func (x *OSInfo) GetRelease() string {
	if x != nil {
		return x.Release
	}
	return ""
}

func (x *OSInfo) GetReleaseId() string {
	if x != nil {
		return x.ReleaseId
	}
	return ""
}

func (x *OSInfo) GetMajorVersion() string {
	if x != nil {
		return x.MajorVersion
	}
	return ""
}

func (x *OSInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *OSInfo) GetEdition() string {
	if x != nil {
		return x.Edition
	}
	return ""
}

func (x *OSInfo) GetEditionId() string {
	if x != nil {
		return x.EditionId
	}
	return ""
}

func (x *OSInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *OSInfo) GetFamilies() []string {
	if x != nil {
		return x.Families
	}
	return nil
}

type FIPSInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Known   bool `protobuf:"varint,1,opt,name=known,proto3" json:"known,omitempty"`
	Enabled bool `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
}

func (x *FIPSInfo) Reset() {
	*x = FIPSInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_info_info_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FIPSInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FIPSInfo) ProtoMessage() {}

func (x *FIPSInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_info_info_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FIPSInfo.ProtoReflect.Descriptor instead.
func (*FIPSInfo) Descriptor() ([]byte, []int) {
	return file_pkg_info_info_proto_rawDescGZIP(), []int{1}
}

func (x *FIPSInfo) GetKnown() bool {
	if x != nil {
		return x.Known
	}
	return false
}

func (x *FIPSInfo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type AppArmorInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Supported bool `protobuf:"varint,1,opt,name=supported,proto3" json:"supported,omitempty"`
	Enabled   bool `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
}

func (x *AppArmorInfo) Reset() {
	*x = AppArmorInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_info_info_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppArmorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppArmorInfo) ProtoMessage() {}

func (x *AppArmorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_info_info_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppArmorInfo.ProtoReflect.Descriptor instead.
func (*AppArmorInfo) Descriptor() ([]byte, []int) {
	return file_pkg_info_info_proto_rawDescGZIP(), []int{2}
}

func (x *AppArmorInfo) GetSupported() bool {
	if x != nil {
		return x.Supported
	}
	return false
}

func (x *AppArmorInfo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type SELinuxInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Supported bool   `protobuf:"varint,1,opt,name=supported,proto3" json:"supported,omitempty"`
	Installed bool   `protobuf:"varint,2,opt,name=installed,proto3" json:"installed,omitempty"`
	Status    string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Type      string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *SELinuxInfo) Reset() {
	*x = SELinuxInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_info_info_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SELinuxInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SELinuxInfo) ProtoMessage() {}

func (x *SELinuxInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_info_info_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SELinuxInfo.ProtoReflect.Descriptor instead.
func (*SELinuxInfo) Descriptor() ([]byte, []int) {
	return file_pkg_info_info_proto_rawDescGZIP(), []int{3}
}

func (x *SELinuxInfo) GetSupported() bool {
	if x != nil {
		return x.Supported
	}
	return false
}

func (x *SELinuxInfo) GetInstalled() bool {
	if x != nil {
		return x.Installed
	}
	return false
}

func (x *SELinuxInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SELinuxInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type PackageManagerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *PackageManagerInfo) Reset() {
	*x = PackageManagerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_info_info_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PackageManagerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageManagerInfo) ProtoMessage() {}

func (x *PackageManagerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_info_info_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageManagerInfo.ProtoReflect.Descriptor instead.
func (*PackageManagerInfo) Descriptor() ([]byte, []int) {
	return file_pkg_info_info_proto_rawDescGZIP(), []int{4}
}

func (x *PackageManagerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PackageManagerInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ServiceManagerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ServiceManagerInfo) Reset() {
	*x = ServiceManagerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_info_info_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceManagerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceManagerInfo) ProtoMessage() {}

func (x *ServiceManagerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_info_info_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceManagerInfo.ProtoReflect.Descriptor instead.
func (*ServiceManagerInfo) Descriptor() ([]byte, []int) {
	return file_pkg_info_info_proto_rawDescGZIP(), []int{5}
}

func (x *ServiceManagerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HostInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Os             *OSInfo             `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Fips           *FIPSInfo           `protobuf:"bytes,2,opt,name=fips,proto3" json:"fips,omitempty"`
	AppArmor       *AppArmorInfo       `protobuf:"bytes,3,opt,name=app_armor,json=appArmor,proto3" json:"app_armor,omitempty"`
	Selinux        *SELinuxInfo        `protobuf:"bytes,4,opt,name=selinux,proto3" json:"selinux,omitempty"`
	PackageManager *PackageManagerInfo `protobuf:"bytes,5,opt,name=package_manager,json=packageManager,proto3" json:"package_manager,omitempty"`
	ServiceManager *ServiceManagerInfo `protobuf:"bytes,6,opt,name=service_manager,json=serviceManager,proto3" json:"service_manager,omitempty"`
}

func (x *HostInfo) Reset() {
	*x = HostInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_info_info_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfo) ProtoMessage() {}

func (x *HostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_info_info_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfo.ProtoReflect.Descriptor instead.
func (*HostInfo) Descriptor() ([]byte, []int) {
	return file_pkg_info_info_proto_rawDescGZIP(), []int{6}
}

func (x *HostInfo) GetOs() *OSInfo {
	if x != nil {
		return x.Os
	}
	return nil
}

func (x *HostInfo) GetFips() *FIPSInfo {
	if x != nil {
		return x.Fips
	}
	return nil
}

func (x *HostInfo) GetAppArmor() *AppArmorInfo {
	if x != nil {
		return x.AppArmor
	}
	return nil
}

func (x *HostInfo) GetSelinux() *SELinuxInfo {
	if x != nil {
		return x.Selinux
	}
	return nil
}

func (x *HostInfo) GetPackageManager() *PackageManagerInfo {
	if x != nil {
		return x.PackageManager
	}
	return nil
}

func (x *HostInfo) GetServiceManager() *ServiceManagerInfo {
	if x != nil {
		return x.ServiceManager
	}
	return nil
}

var File_pkg_info_info_proto protoreflect.FileDescriptor

var file_pkg_info_info_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x6b, 0x67, 0x2f, 0x69, 0x6e, 0x66, 0x6f, 0x2f, 0x69, 0x6e, 0x66, 0x6f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0xb6, 0x02, 0x0a, 0x06,
	0x4f, 0x53, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x23,
	0x0a, 0x0d, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x6c, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x6c, 0x79, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d,
	0x6d, 0x61, 0x6a, 0x6f, 0x72, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x61, 0x6a, 0x6f, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x65,
	0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x64, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x63, 0x68, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x63, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x61, 0x6d, 0x69,
	0x6c, 0x69, 0x65, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x66, 0x61, 0x6d, 0x69,
	0x6c, 0x69, 0x65, 0x73, 0x22, 0x3a, 0x0a, 0x08, 0x46, 0x49, 0x50, 0x53, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x14, 0x0a, 0x05, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x05, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64,
	0x22, 0x46, 0x0a, 0x0c, 0x41, 0x70, 0x70, 0x41, 0x72, 0x6d, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x09, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x22, 0x75, 0x0a, 0x0b, 0x53, 0x45, 0x4c, 0x69,
	0x6e, 0x75, 0x78, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x75, 0x70, 0x70, 0x6f,
	0x72, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x73, 0x75, 0x70, 0x70,
	0x6f, 0x72, 0x74, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c,
	0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c,
	0x6c, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22,
	0x3c, 0x0a, 0x12, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x28, 0x0a,
	0x12, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xb0, 0x02, 0x0a, 0x08, 0x48, 0x6f, 0x73, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x02, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x4f, 0x53, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x02,
	0x6f, 0x73, 0x12, 0x22, 0x0a, 0x04, 0x66, 0x69, 0x70, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x46, 0x49, 0x50, 0x53, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x04, 0x66, 0x69, 0x70, 0x73, 0x12, 0x2f, 0x0a, 0x09, 0x61, 0x70, 0x70, 0x5f, 0x61, 0x72,
	0x6d, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x69, 0x6e, 0x66, 0x6f,
	0x2e, 0x41, 0x70, 0x70, 0x41, 0x72, 0x6d, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x61,
	0x70, 0x70, 0x41, 0x72, 0x6d, 0x6f, 0x72, 0x12, 0x2b, 0x0a, 0x07, 0x73, 0x65, 0x6c, 0x69, 0x6e,
	0x75, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x69, 0x6e, 0x66, 0x6f, 0x2e,
	0x53, 0x45, 0x4c, 0x69, 0x6e, 0x75, 0x78, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x73, 0x65, 0x6c,
	0x69, 0x6e, 0x75, 0x78, 0x12, 0x41, 0x0a, 0x0f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x5f,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x4d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0e, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12, 0x41, 0x0a, 0x0f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x72, 0x69, 0x70, 0x70, 0x73, 0x6f,
	0x66, 0x74, 0x2f, 0x66, 0x6f, 0x72, 0x67, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x69, 0x6e, 0x66,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_info_info_proto_rawDescOnce sync.Once
	file_pkg_info_info_proto_rawDescData = file_pkg_info_info_proto_rawDesc
)

func file_pkg_info_info_proto_rawDescGZIP() []byte {
	file_pkg_info_info_proto_rawDescOnce.Do(func() {
		file_pkg_info_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_info_info_proto_rawDescData)
	})
	return file_pkg_info_info_proto_rawDescData
}

var file_pkg_info_info_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_info_info_proto_goTypes = []interface{}{
	(*OSInfo)(nil),             // 0: info.OSInfo
	(*FIPSInfo)(nil),           // 1: info.FIPSInfo
	(*AppArmorInfo)(nil),       // 2: info.AppArmorInfo
	(*SELinuxInfo)(nil),        // 3: info.SELinuxInfo
	(*PackageManagerInfo)(nil), // 4: info.PackageManagerInfo
	(*ServiceManagerInfo)(nil), // 5: info.ServiceManagerInfo
	(*HostInfo)(nil),           // 6: info.HostInfo
}
var file_pkg_info_info_proto_depIdxs = []int32{
	0, // 0: info.HostInfo.os:type_name -> info.OSInfo
	1, // 1: info.HostInfo.fips:type_name -> info.FIPSInfo
	2, // 2: info.HostInfo.app_armor:type_name -> info.AppArmorInfo
	3, // 3: info.HostInfo.selinux:type_name -> info.SELinuxInfo
	4, // 4: info.HostInfo.package_manager:type_name -> info.PackageManagerInfo
	5, // 5: info.HostInfo.service_manager:type_name -> info.ServiceManagerInfo
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_info_info_proto_init() }
func file_pkg_info_info_proto_init() {
	if File_pkg_info_info_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_info_info_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OSInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_info_info_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FIPSInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_info_info_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppArmorInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_info_info_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SELinuxInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_info_info_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PackageManagerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_info_info_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceManagerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_info_info_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_info_info_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_info_info_proto_goTypes,
		DependencyIndexes: file_pkg_info_info_proto_depIdxs,
		MessageInfos:      file_pkg_info_info_proto_msgTypes,
	}.Build()
	File_pkg_info_info_proto = out.File
	file_pkg_info_info_proto_rawDesc = nil
	file_pkg_info_info_proto_goTypes = nil
	file_pkg_info_info_proto_depIdxs = nil
}
