// Code generated by scriptimport.  DO NOT EDIT.

// This script is used to discover OS information on Windows systems.
// It returns a JSON object with the OS name and version.

package info

const osWindowsDiscoveryScript = `` +
    `Import-Module -Name Dism; ` +
    `$friendlyName = (Get-CimInstance -ClassName Win32_OperatingSystem).Caption; ` +
    `$version = [System.Environment]::OSVersion.Version.ToString(); ` +
    `$osArch = (Get-CimInstance -ClassName Win32_OperatingSystem).OSArchitecture; ` +
    `$procArch = $env:PROCESSOR_ARCHITECTURE; ` +
    `$output = @{ ` +
    `os_friendly_name = $friendlyName; ` +
    `os_version = $version; ` +
    `os_bits = $osArch; ` +
    `processor_arch = $procArch; ` +
    `}; ` +
    `$json = $output | ConvertTo-Json -Depth 3; ` +
    `Write-Host $json`
