// Code generated by scriptimport.  DO NOT EDIT.

// Copyright (c) Forge
// SPDX-License-Identifier: MPL-2.0

// This script is used to discover package manager information on various POSIX systems.
// It returns whether specific package managers are installed and available.

package info

const PackageManagerDiscoveryScript = `` +
    `qopensys_pkgs_bin_yum_exists="0"; ` +
    `usr_bin_installp_exists="0"; ` +
    `usr_sbin_sorcery_exists="0"; ` +
    `usr_bin_swupd_exists="0"; ` +
    `usr_local_sbin_pkg_exists="0"; ` +
    `usr_bin_xbps_install_exists="0"; ` +
    `usr_bin_pkg_exists="0"; ` +
    `usr_sbin_pkgadd_exists="0"; ` +
    `usr_bin_emerge_exists="0"; ` +
    `usr_sbin_swlist_exists="0"; ` +
    `usr_sbin_pkg_exists="0"; ` +
    `sbin_apk_exists="0"; ` +
    `opt_homebrew_bin_brew_exists="0"; ` +
    `usr_local_bin_brew_exists="0"; ` +
    `opt_local_bin_port_exists="0"; ` +
    `opt_tools_bin_pkgin_exists="0"; ` +
    `opt_local_bin_pkgin_exists="0"; ` +
    `usr_pkg_bin_pkgin_exists="0"; ` +
    `bin_opkg_exists="0"; ` +
    `usr_bin_pacman_exists="0"; ` +
    `usr_sbin_urpmi_exists="0"; ` +
    `usr_bin_zypper_exists="0"; ` +
    `usr_bin_apt_get_exists="0"; ` +
    `usr_bin_dnf5_exists="0"; ` +
    `usr_bin_dnf_3_exists="0"; ` +
    `usr_bin_dnf_exists="0"; ` +
    `usr_bin_yum_exists="0"; ` +
    `apt_provided_by_rpm_package=""; ` +
    `if [ -x /QOpenSys/pkgs/bin/yum ]; then ` +
    `qopensys_pkgs_bin_yum_exists="1"; ` +
    `fi; ` +
    `if [ -x /usr/bin/installp ]; then ` +
    `usr_bin_installp_exists="1"; ` +
    `fi; ` +
    `if [ -x /usr/sbin/sorcery ]; then ` +
    `usr_sbin_sorcery_exists="1"; ` +
    `fi; ` +
    `if [ -x /usr/bin/swupd ]; then ` +
    `usr_bin_swupd_exists="1"; ` +
    `fi; ` +
    `if [ -x /usr/local/sbin/pkg ]; then ` +
    `usr_local_sbin_pkg_exists="1"; ` +
    `fi; ` +
    `if [ -x /usr/bin/xbps-install ]; then ` +
    `usr_bin_xbps_install_exists="1"; ` +
    `fi; ` +
    `if [ -x /usr/bin/pkg ]; then ` +
    `usr_bin_pkg_exists="1"; ` +
    `fi; ` +
    `if [ -x /usr/sbin/pkgadd ]; then ` +
    `usr_sbin_pkgadd_exists="1"; ` +
    `fi; ` +
    `if [ -x /usr/bin/emerge ]; then ` +
    `usr_bin_emerge_exists="1"; ` +
    `fi; ` +
    `if [ -x /usr/sbin/swlist ]; then ` +
    `usr_sbin_swlist_exists="1"; ` +
    `fi; ` +
    `if [ -x /usr/sbin/pkg ]; then ` +
    `usr_sbin_pkg_exists="1"; ` +
    `fi; ` +
    `if [ -x /sbin/apk ]; then ` +
    `sbin_apk_exists="1"; ` +
    `fi; ` +
    `if [ -x /opt/homebrew/bin/brew ]; then ` +
    `opt_homebrew_bin_brew_exists="1"; ` +
    `fi; ` +
    `if [ -x /usr/local/bin/brew ]; then ` +
    `usr_local_bin_brew_exists="1"; ` +
    `fi; ` +
    `if [ -x /opt/local/bin/port ]; then ` +
    `opt_local_bin_port_exists="1"; ` +
    `fi; ` +
    `if [ -x /opt/tools/bin/pkgin ]; then ` +
    `opt_tools_bin_pkgin_exists="1"; ` +
    `fi; ` +
    `if [ -x /opt/local/bin/pkgin ]; then ` +
    `opt_local_bin_pkgin_exists="1"; ` +
    `fi; ` +
    `if [ -x /usr/pkg/bin/pkgin ]; then ` +
    `usr_pkg_bin_pkgin_exists="1"; ` +
    `fi; ` +
    `if [ -x /bin/opkg ]; then ` +
    `bin_opkg_exists="1"; ` +
    `fi; ` +
    `if [ -x /usr/bin/pacman ]; then ` +
    `usr_bin_pacman_exists="1"; ` +
    `fi; ` +
    `if [ -x /usr/sbin/urpmi ]; then ` +
    `usr_sbin_urpmi_exists="1"; ` +
    `fi; ` +
    `if [ -x /usr/bin/zypper ]; then ` +
    `usr_bin_zypper_exists="1"; ` +
    `fi; ` +
    `if [ -x /usr/bin/apt-get ]; then ` +
    `usr_bin_apt_get_exists="1"; ` +
    `fi; ` +
    `if [ -x /usr/bin/dnf5 ]; then ` +
    `usr_bin_dnf5_exists="1"; ` +
    `fi; ` +
    `if [ -x /usr/bin/dnf-3 ]; then ` +
    `usr_bin_dnf_3_exists="1"; ` +
    `fi; ` +
    `if [ -x /usr/bin/dnf ]; then ` +
    `usr_bin_dnf_exists="1"; ` +
    `fi; ` +
    `if [ -x /usr/bin/yum ]; then ` +
    `usr_bin_yum_exists="1"; ` +
    `fi; ` +
    `if [ "$usr_bin_apt_get_exists" = "1" ] && [ -x /usr/bin/rpm ]; then ` +
    `apt_provided_by_rpm_package=$(/usr/bin/rpm -q --whatprovides /usr/bin/apt-get || echo ""); ` +
    `fi; ` +
    `printf "{\"qopensys_pkgs_bin_yum_exists\": \"%s\", \"usr_bin_installp_exists\": \"%s\", \"usr_sbin_sorcery_exists\": \"%s\", " ` +
    `"$qopensys_pkgs_bin_yum_exists" ` +
    `"$usr_bin_installp_exists" ` +
    `"$usr_sbin_sorcery_exists"; ` +
    `printf "\"usr_bin_swupd_exists\": \"%s\", \"usr_local_sbin_pkg_exists\": \"%s\", \"usr_bin_xbps_install_exists\": \"%s\", " ` +
    `"$usr_bin_swupd_exists" ` +
    `"$usr_local_sbin_pkg_exists" ` +
    `"$usr_bin_xbps_install_exists"; ` +
    `printf "\"usr_bin_pkg_exists\": \"%s\", \"usr_sbin_pkgadd_exists\": \"%s\", \"usr_bin_emerge_exists\": \"%s\", " ` +
    `"$usr_bin_pkg_exists" ` +
    `"$usr_sbin_pkgadd_exists" ` +
    `"$usr_bin_emerge_exists"; ` +
    `printf "\"usr_sbin_swlist_exists\": \"%s\", \"usr_sbin_pkg_exists\": \"%s\", \"sbin_apk_exists\": \"%s\", " ` +
    `"$usr_sbin_swlist_exists" ` +
    `"$usr_sbin_pkg_exists" ` +
    `"$sbin_apk_exists"; ` +
    `printf "\"opt_homebrew_bin_brew_exists\": \"%s\", \"usr_local_bin_brew_exists\": \"%s\", \"opt_local_bin_port_exists\": \"%s\", " ` +
    `"$opt_homebrew_bin_brew_exists" ` +
    `"$usr_local_bin_brew_exists" ` +
    `"$opt_local_bin_port_exists"; ` +
    `printf "\"opt_tools_bin_pkgin_exists\": \"%s\", \"opt_local_bin_pkgin_exists\": \"%s\", \"usr_pkg_bin_pkgin_exists\": \"%s\", " ` +
    `"$opt_tools_bin_pkgin_exists" ` +
    `"$opt_local_bin_pkgin_exists" ` +
    `"$usr_pkg_bin_pkgin_exists"; ` +
    `printf "\"bin_opkg_exists\": \"%s\", \"usr_bin_pacman_exists\": \"%s\", \"usr_sbin_urpmi_exists\": \"%s\", \"usr_bin_zypper_exists\": \"%s\", " ` +
    `"$bin_opkg_exists" ` +
    `"$usr_bin_pacman_exists" ` +
    `"$usr_sbin_urpmi_exists" ` +
    `"$usr_bin_zypper_exists"; ` +
    `printf "\"usr_bin_apt_get_exists\": \"%s\", \"usr_bin_dnf5_exists\": \"%s\", \"usr_bin_dnf_3_exists\": \"%s\", \"usr_bin_dnf_exists\": \"%s\", " ` +
    `"$usr_bin_apt_get_exists" ` +
    `"$usr_bin_dnf5_exists" ` +
    `"$usr_bin_dnf_3_exists" ` +
    `"$usr_bin_dnf_exists"; ` +
    `printf "\"usr_bin_yum_exists\": \"%s\", \"apt_provided_by_rpm_package\": \"%s\"}\n" ` +
    `"$usr_bin_yum_exists" ` +
    `"$(escape_json "$apt_provided_by_rpm_package")"`
