// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.6
// source: pkg/plugin/v1/plugin.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	PluginV1Service_GetModules_FullMethodName = "/plugin.v1.PluginV1Service/GetModules"
	PluginV1Service_RunModule_FullMethodName  = "/plugin.v1.PluginV1Service/RunModule"
	PluginV1Service_Shutdown_FullMethodName   = "/plugin.v1.PluginV1Service/Shutdown"
)

// PluginV1ServiceClient is the client API for PluginV1Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginV1ServiceClient interface {
	GetModules(ctx context.Context, in *GetModulesRequest, opts ...grpc.CallOption) (*GetModulesResponse, error)
	RunModule(ctx context.Context, in *RunModuleRequest, opts ...grpc.CallOption) (*RunModuleResponse, error)
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
}

type pluginV1ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginV1ServiceClient(cc grpc.ClientConnInterface) PluginV1ServiceClient {
	return &pluginV1ServiceClient{cc}
}

func (c *pluginV1ServiceClient) GetModules(ctx context.Context, in *GetModulesRequest, opts ...grpc.CallOption) (*GetModulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModulesResponse)
	err := c.cc.Invoke(ctx, PluginV1Service_GetModules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginV1ServiceClient) RunModule(ctx context.Context, in *RunModuleRequest, opts ...grpc.CallOption) (*RunModuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunModuleResponse)
	err := c.cc.Invoke(ctx, PluginV1Service_RunModule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginV1ServiceClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, PluginV1Service_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginV1ServiceServer is the server API for PluginV1Service service.
// All implementations must embed UnimplementedPluginV1ServiceServer
// for forward compatibility
type PluginV1ServiceServer interface {
	GetModules(context.Context, *GetModulesRequest) (*GetModulesResponse, error)
	RunModule(context.Context, *RunModuleRequest) (*RunModuleResponse, error)
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	mustEmbedUnimplementedPluginV1ServiceServer()
}

// UnimplementedPluginV1ServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPluginV1ServiceServer struct {
}

func (UnimplementedPluginV1ServiceServer) GetModules(context.Context, *GetModulesRequest) (*GetModulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModules not implemented")
}
func (UnimplementedPluginV1ServiceServer) RunModule(context.Context, *RunModuleRequest) (*RunModuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunModule not implemented")
}
func (UnimplementedPluginV1ServiceServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedPluginV1ServiceServer) mustEmbedUnimplementedPluginV1ServiceServer() {}

// UnsafePluginV1ServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginV1ServiceServer will
// result in compilation errors.
type UnsafePluginV1ServiceServer interface {
	mustEmbedUnimplementedPluginV1ServiceServer()
}

func RegisterPluginV1ServiceServer(s grpc.ServiceRegistrar, srv PluginV1ServiceServer) {
	s.RegisterService(&PluginV1Service_ServiceDesc, srv)
}

func _PluginV1Service_GetModules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginV1ServiceServer).GetModules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginV1Service_GetModules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginV1ServiceServer).GetModules(ctx, req.(*GetModulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginV1Service_RunModule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunModuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginV1ServiceServer).RunModule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginV1Service_RunModule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginV1ServiceServer).RunModule(ctx, req.(*RunModuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginV1Service_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginV1ServiceServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginV1Service_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginV1ServiceServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginV1Service_ServiceDesc is the grpc.ServiceDesc for PluginV1Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginV1Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.v1.PluginV1Service",
	HandlerType: (*PluginV1ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetModules",
			Handler:    _PluginV1Service_GetModules_Handler,
		},
		{
			MethodName: "RunModule",
			Handler:    _PluginV1Service_RunModule_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _PluginV1Service_Shutdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/plugin/v1/plugin.proto",
}
