# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define "cmd" do |cmd|
        cmd.vm.box = "jtarpley/w2025_base"
        cmd.vm.provision "shell", path: "cmd.ps1"
    end

    config.vm.define "windows" do |windows|
        windows.vm.box = "jtarpley/w2025_base"
        windows.vm.provision "shell", path: "powershell.ps1"
    end
end
